using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Security.Cryptography;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using Microsoft.Win32;

namespace LegendsCompanion {
public partial class MainWindow:Window {
 public static string Home=AppDomain.CurrentDomain.BaseDirectory;
 string store=Path.Combine(Home,"data"),researchPath,settingsPath; Settings settings; ResearchFile research;
 List<Achievement> achievements=new List<Achievement>();List<Row> joined=new List<Row>();List<Row> filtered=new List<Row>();
 TextBox source,search,classFilter,raceFilter,notes,sources,bottleneck; ComboBox group,state,era,risk,near,metaMatch,tierEdit,riskEdit,eraEdit,difficulty,travel;
 MultiFilter category,region,zone;CheckBox matchingOptions;TextBox classEdit,raceEdit,personalNotes;CheckBox detours;TextBlock summary,status,detailTitle,basis,why;DataGrid grid,farms;TextBox requirements,completionGuide;
 ObservableCollection<Farm> editFarms=new ObservableCollection<Farm>(); Row editing;string editBaseline="";bool dirty=false,binding=false,ready=false,closing=false;
 long loadedExportStamp; LiveMonitor live; string loadedHash="",candidateHash="",lastSuccess="Never";DispatcherTimer timer;
 StackPanel filterPanel; Grid bodyGrid; ScrollViewer detailScroller; DockPanel detailHost; GridSplitter bodySplitter; Button filtersButton,tableButton,detailRail; bool detailsOpen=false;
 public MainWindow(){
  Title="EQ Legends Achievement Companion";Width=920;Height=820;MinWidth=320;MinHeight=400;Background=Palette.Background;FontFamily=new FontFamily("Segoe UI");FontSize=13;
  using(var iconStream=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("AchievementIcon")){
   if(iconStream!=null){Icon=BitmapFrame.Create(iconStream,BitmapCreateOptions.None,BitmapCacheOption.OnLoad);}
  }
  researchPath=Path.Combine(store,"research.json");settingsPath=Path.Combine(store,"settings.json");
  settings=File.Exists(settingsPath)?Data.Load<Settings>(settingsPath):new Settings();
  if(settings.Live==null)settings.Live=new LiveOptions();if(!settings.TileLayoutInitialized){settings.FiltersHidden=true;settings.TableOnly=false;settings.RecentFirst=true;settings.TileLayoutInitialized=true;}
  research=File.Exists(researchPath)?Data.Load<ResearchFile>(researchPath):null;
  if(research!=null && (research.Version!=1 || research.Items==null || research.Items.GroupBy(x=>x.Key).Any(x=>x.Count()>1)))throw new Exception("Research data is invalid. Restore a backup before continuing; no data has been overwritten.");
  Loaded+=(s,e)=>OfferSetup();PrepareProfiles();InitializeTheme();Guides.Load(Home);Build();InstallWindowFrame();BuildUpdater();RestoreWindowPlacement(); ready=true;LoadSource(true);RefreshFilters();RestoreFilters();Apply();SetPresentation(false);
  timer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(2)};timer.Tick+=(s,e)=>Poll();timer.Start();
  if(!Environment.GetCommandLineArgs().Any(x=>x=="--test"||x=="--preview")){if(settings.Live==null)settings.Live=new LiveOptions();if(String.IsNullOrWhiteSpace(settings.Live.Path)&&!String.IsNullOrWhiteSpace(settings.SourcePath)){string stem=Path.GetFileNameWithoutExtension(settings.SourcePath).Replace("-Achievements","");string candidate=Path.Combine(Path.GetDirectoryName(settings.SourcePath),"Logs","eqlog_"+stem+".txt");if(File.Exists(candidate))settings.Live.Path=candidate;}live=new LiveMonitor(settings.Live,()=>achievements,()=>settings.SourcePath+loadedHash+loadedExportStamp);live.Notified+=LiveProgress;live.SoundChanged+=SavePopupSound;live.ResetProgress+=ClearLiveTiles;combatPath.Text=settings.Live.Path;liveState.Text=live.Status;}
  Closing+=(s,e)=>{if(!ResolveEdits()){e.Cancel=true;return;}RememberFilters();RememberProfile();SaveWindowPlacement();closing=true;timer.Stop();if(highlightTimer!=null)highlightTimer.Stop();if(live!=null)live.Dispose();};
 }
 TextBlock Text(string value,int size=13){return new TextBlock{Text=value,FontSize=size,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,3,0,5)};}
 Button Button(string label,Action action){var b=new Button{Content=label,Padding=new Thickness(12,6,12,6),Margin=new Thickness(4,0,4,0)};b.Click+=(s,e)=>action();return b;}
 ComboBox Combo(params string[] values){var c=new ComboBox{MinWidth=120,Margin=new Thickness(0,2,12,5),Padding=new Thickness(5)};foreach(var v in values)c.Items.Add(v);c.SelectedIndex=0;return c;}
 TextBox Input(){return new TextBox{Padding=new Thickness(6),Margin=new Thickness(0,2,12,5)};}
 void Labeled(Panel parent,string label,UIElement control){var p=new StackPanel{Margin=new Thickness(0,0,0,5)};p.Children.Add(Text(label));p.Children.Add(control);parent.Children.Add(p);}
 void Build(){
  var root=new DockPanel{Margin=new Thickness(8),Background=Palette.Background};Content=root;
  BuildTrackerHeader(root);BuildOpacityControl();
  var top=new StackPanel();filterPanel=top;var filterScroll=new ScrollViewer{Content=top,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};DockPanel.SetDock(filterScroll,Dock.Top);root.Children.Add(filterScroll);
  summary=Text("Waiting for an achievement export",16);summary.FontSize=12;summary.Padding=new Thickness(6);BuildProgressOverview(top);
  var controls=new WrapPanel();top.Children.Add(controls);
  group=Combo("ALL","BANESTRIKE","UNLOCKS","SLAYER","EXPLORATION","PROGRESSION","SKILLS","TRADESKILLS");Labeled(controls,"Focus",group);
  category=new MultiFilter("All categories");category.MaxWidth=215;Labeled(controls,"Category",category);
  state=Combo("Incomplete","All states","Complete");Labeled(controls,"State",state);
  near=Combo("Any progress","90% or more","50% or more","10 or fewer remaining");Labeled(controls,"Progress",near);
  era=Combo("All availability","Unknown","Observed EQL","Confirmed EQL","Unavailable","Quest placeholder (TXT)");Labeled(controls,"Era availability",era);
  risk=Combo("All risks","Unknown","Low","Medium","High","Not applicable","See location notes");Labeled(controls,"Faction risk",risk);
  var locations=new WrapPanel();top.Children.Add(locations);region=new MultiFilter("All regions");Labeled(locations,"Farming region",region);zone=new MultiFilter("All zones");Labeled(locations,"Mob location",zone);
  detours=new CheckBox{Content="Include travel-route detours",VerticalAlignment=VerticalAlignment.Center,Margin=new Thickness(5,16,15,0)};detours.Visibility=Visibility.Collapsed;
  var resetFilters=Button("Reset filters",Reset);resetFilters.VerticalAlignment=VerticalAlignment.Bottom;resetFilters.Margin=new Thickness(0,0,4,10);locations.Children.Add(resetFilters);
  matchingOptions=new CheckBox{Content="Zone optimized Results",Margin=new Thickness(4,6,4,6)};top.Children.Add(matchingOptions);matchingOptions.Checked+=(s,e)=>Apply();matchingOptions.Unchecked+=(s,e)=>Apply();var searches=new WrapPanel();top.Children.Add(searches);search=Input();search.Width=290;Labeled(searches,"Search achievement, mob or notes",search);classFilter=Input();classFilter.Width=150;Labeled(searches,"Class relevance",classFilter);raceFilter=Input();raceFilter.Width=150;Labeled(searches,"Race relevance",raceFilter);metaMatch=Combo("All research","Missing research","Has research");Labeled(searches,"Research coverage",metaMatch);
  var advancedFilters=new WrapPanel();
  foreach(FrameworkElement control in new FrameworkElement[]{near,era,risk,classFilter,raceFilter,metaMatch}){
   var wrapper=(FrameworkElement)control.Parent;var owner=(Panel)wrapper.Parent;owner.Children.Remove(wrapper);advancedFilters.Children.Add(wrapper);
  }
  var searchWrapper=(FrameworkElement)search.Parent;searches.Children.Remove(searchWrapper);search.HorizontalAlignment=HorizontalAlignment.Stretch;var searchStack=(StackPanel)searchWrapper;searchStack.Children.RemoveAt(0);top.Children.Remove(matchingOptions);searchStack.Children.Insert(0,matchingOptions);
  searchStack.Children.Remove(search);var searchHost=new Grid{Width=290};searchHost.Children.Add(search);
  var placeholder=new TextBlock{Text="Search Achievement, Mob, Notes",Foreground=Palette.Muted,Margin=new Thickness(7,0,0,0),VerticalAlignment=VerticalAlignment.Center,IsHitTestVisible=false};
  searchHost.Children.Add(placeholder);Action hint=()=>placeholder.Visibility=search.IsKeyboardFocusWithin||search.Text.Length>0?Visibility.Collapsed:Visibility.Visible;search.TextChanged+=(s,e)=>hint();search.GotKeyboardFocus+=(s,e)=>hint();search.LostKeyboardFocus+=(s,e)=>hint();hint();searchStack.Children.Add(searchHost);controls.Children.Insert(0,searchWrapper);while(locations.Children.Count>0){var child=locations.Children[0];locations.Children.RemoveAt(0);controls.Children.Add(child);}top.Children.Remove(locations);top.Children.Remove(searches);
  top.Children.Add(new Expander{Header="Advanced filters",Content=advancedFilters,Margin=new Thickness(0,2,0,6)});
  status=Text("",12);status.Padding=new Thickness(2);status.TextWrapping=TextWrapping.NoWrap;status.TextTrimming=TextTrimming.CharacterEllipsis;status.SetBinding(TextBlock.ToolTipProperty,new Binding("Text"){Source=status});DockPanel.SetDock(status,Dock.Bottom);root.Children.Add(status);
  var body=new Grid();bodyGrid=body;body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1,GridUnitType.Star)});body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(8)});body.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(2,GridUnitType.Star)});root.Children.Add(body);
  grid=new DataGrid{ToolTip="Select cells, then press Ctrl+C to copy. Shift selects a range; Ctrl adds cells. Click a row header to select the whole row.",AutoGenerateColumns=false,IsReadOnly=true,SelectionMode=DataGridSelectionMode.Extended,SelectionUnit=DataGridSelectionUnit.CellOrRowHeader,ClipboardCopyMode=DataGridClipboardCopyMode.ExcludeHeader,CanUserAddRows=false,RowHeight=32,HeadersVisibility=DataGridHeadersVisibility.All,GridLinesVisibility=DataGridGridLinesVisibility.Horizontal};
  AddColumn(grid,"Achievement","Achievement",230);AddColumn(grid,"Destination / farming zone","Location",180);AddColumn(grid,"Mobs / item source & turn-in","Mobs",300);AddColumn(grid,"Remaining","Remaining",85);AddColumn(grid,"Progress","Progress",70);
  grid.EnableColumnVirtualization=false;grid.FrozenColumnCount=0;grid.RowHeight=30;grid.MinRowHeight=30;
  var cellStyle=new Style(typeof(TextBlock));cellStyle.Setters.Add(new Setter(TextBlock.TextWrappingProperty,TextWrapping.NoWrap));cellStyle.Setters.Add(new Setter(TextBlock.TextTrimmingProperty,TextTrimming.CharacterEllipsis));cellStyle.Setters.Add(new Setter(TextBlock.ToolTipProperty,new Binding("Text"){RelativeSource=new RelativeSource(RelativeSourceMode.Self)}));cellStyle.Setters.Add(new Setter(TextBlock.MarginProperty,new Thickness(4)));foreach(DataGridTextColumn col in grid.Columns){col.ElementStyle=cellStyle;}
  body.Children.Add(grid);var split=new GridSplitter{Width=7,HorizontalAlignment=HorizontalAlignment.Stretch};bodySplitter=split;Grid.SetColumn(split,1);body.Children.Add(split);
  detailHost=new DockPanel();Grid.SetColumn(detailHost,2);body.Children.Add(detailHost);
  var panelHeading=new DockPanel{Margin=new Thickness(10,0,0,8)};DockPanel.SetDock(panelHeading,Dock.Top);detailHost.Children.Add(panelHeading);var shrink=Button("Shrink ›",ShrinkDetails);DockPanel.SetDock(shrink,Dock.Right);panelHeading.Children.Add(shrink);panelHeading.Children.Add(Text("Achievement research",15));
  detailRail=Button("‹",OpenDetails);detailRail.ToolTip="Reopen selected achievement research";detailRail.Margin=new Thickness(0);detailRail.Padding=new Thickness(3);Grid.SetColumn(detailRail,2);body.Children.Add(detailRail);
  var scroller=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto};detailScroller=scroller;detailHost.Children.Add(scroller);var detail=new StackPanel{Margin=new Thickness(10,0,0,0)};scroller.Content=detail;
  detailTitle=Text("Select an achievement",18);detail.Children.Add(detailTitle);basis=Text("");detail.Children.Add(basis);why=Text("");detail.Children.Add(why);
  requirements=new TextBox{IsReadOnly=true,TextWrapping=TextWrapping.Wrap,AcceptsReturn=true,MinHeight=0,MaxHeight=90,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Background=Palette.Background,BorderThickness=new Thickness(0),Padding=new Thickness(3)};Labeled(detail,"Achievement requirements",requirements);
  completionGuide=new TextBox{IsReadOnly=true,TextWrapping=TextWrapping.Wrap,AcceptsReturn=true,MinHeight=100,MaxHeight=260,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Padding=new Thickness(7)};Labeled(detail,"Completion guide",completionGuide);BuildMobNames(detail);personalNotes=Input();personalNotes.AcceptsReturn=true;personalNotes.TextWrapping=TextWrapping.Wrap;personalNotes.MinHeight=90;personalNotes.MaxHeight=220;personalNotes.VerticalScrollBarVisibility=ScrollBarVisibility.Auto;Labeled(detail,"Personal notes (saved here only; do not affect the table)",personalNotes);
  detail.Children.Add(Text("Available mob locations",15));detail.Children.Add(Button("Save research",()=>SaveResearch()));detail.Children.Add(Text("Locations and targets. For turn-ins, include the item source and turn-in NPC.",12));
  farms=new DataGrid{AutoGenerateColumns=false,CanUserAddRows=true,CanUserDeleteRows=true,MinHeight=110,MaxHeight=220,ItemsSource=editFarms,HeadersVisibility=DataGridHeadersVisibility.Column};
  var useBox=new FrameworkElementFactory(typeof(CheckBox));useBox.SetBinding(CheckBox.IsCheckedProperty,new Binding("Selected"){Mode=BindingMode.TwoWay,UpdateSourceTrigger=UpdateSourceTrigger.PropertyChanged});useBox.AddHandler(CheckBox.ClickEvent,new RoutedEventHandler((sender,args)=>{if(binding)return;var chosen=((CheckBox)sender).DataContext as Farm;if(chosen==null)return;if(chosen.Selected)foreach(var other in editFarms.Where(f=>f!=chosen&&f.Kind!="Required stop"&&chosen.Kind!="Required stop"))other.Selected=false;dirty=true;}));farms.Columns.Add(new DataGridTemplateColumn{Header="Use in table",Width=85,CellTemplate=new DataTemplate{VisualTree=useBox}});AddColumn(farms,"Zone","Zone",130);AddColumn(farms,"Option type","Kind",110);farms.Columns.Last().IsReadOnly=true;AddColumn(farms,"Region","Region",100);AddColumn(farms,"Mobs / item source & turn-in","Mobs",300);AddColumn(farms,"Faction hit","Faction",180);AddColumn(farms,"Druid / Wizard ports & route","PortRoute",350);var routeColumn=(DataGridTextColumn)farms.Columns.Last();var routeView=new Style(typeof(TextBlock));routeView.Setters.Add(new Setter(TextBlock.TextWrappingProperty,TextWrapping.Wrap));routeColumn.ElementStyle=routeView;var routeEdit=new Style(typeof(TextBox));routeEdit.Setters.Add(new Setter(TextBox.AcceptsReturnProperty,true));routeEdit.Setters.Add(new Setter(TextBox.TextWrappingProperty,TextWrapping.Wrap));routeEdit.Setters.Add(new Setter(TextBox.MinHeightProperty,65.0));routeColumn.EditingElementStyle=routeEdit;farms.CellEditEnding+=(s,e)=>{if(!binding)dirty=true;};farms.RowEditEnding+=(s,e)=>{if(!binding)dirty=true;};editFarms.CollectionChanged+=(s,e)=>{if(!binding)dirty=true;};detail.Children.Add(farms);
  var researchDetails=new StackPanel();detail.Children.Add(new Expander{Header="Edit research details",Content=researchDetails});detail=researchDetails;
  tierEdit=Combo("","Automatic","A - Quick Win","B - Efficient","C - Grind / Stack","D - Faction Cleanup","E - Defer / Bottleneck");Labeled(detail,"Action tier",tierEdit);var fieldRow=new WrapPanel();detail.Children.Add(fieldRow);riskEdit=Combo("Unknown","Low","Medium","High");Labeled(fieldRow,"Faction risk",riskEdit);eraEdit=Combo("","Raid-only","Inaccessible","Not implemented","Unavailable");Labeled(fieldRow,"Availability",eraEdit);
  var costs=fieldRow;difficulty=Combo("1","2","3","4","5");Labeled(costs,"Difficulty (1–5)",difficulty);travel=Combo("0","1","2","3","4","5");Labeled(costs,"Travel cost (0–5)",travel);
  bottleneck=Input();Labeled(detail,"Bottleneck / access requirement",bottleneck);classEdit=Input();Labeled(detail,"Class relevance",classEdit);raceEdit=Input();Labeled(detail,"Race relevance",raceEdit);
  notes=Input();notes.AcceptsReturn=true;notes.TextWrapping=TextWrapping.Wrap;notes.MinHeight=85;Labeled(detail,"Notes",notes);sources=Input();sources.AcceptsReturn=true;sources.TextWrapping=TextWrapping.Wrap;sources.MinHeight=50;Labeled(detail,"Research sources",sources);
  var saveRow=new WrapPanel();saveRow.Children.Add(Button("Save research",()=>SaveResearch()));saveRow.Children.Add(Button("Discard edits",()=>{dirty=false;Edit(editing);}));detail.Children.Add(saveRow);
  foreach(var c in new[]{group,state,near,era,risk,metaMatch})c.SelectionChanged+=(s,e)=>{if(ready)Apply();};category.Changed+=(s,e)=>{if(ready)Apply();};zone.Changed+=(s,e)=>{if(ready)Apply();};region.Changed+=(s,e)=>{if(ready){RefreshZones();Apply();}};
  foreach(var t in new[]{search,classFilter,raceFilter})t.TextChanged+=(s,e)=>{if(ready)Apply();};detours.Checked+=(s,e)=>Apply();detours.Unchecked+=(s,e)=>Apply();
  foreach(var t in new[]{notes,personalNotes,sources,bottleneck,classEdit,raceEdit})t.TextChanged+=(s,e)=>{if(!binding)dirty=true;};foreach(var c in new[]{tierEdit,riskEdit,eraEdit,difficulty,travel})c.SelectionChanged+=(s,e)=>{if(!binding)dirty=true;};
  grid.CurrentCellChanged+=(s,e)=>{if(binding)return;var active=grid.CurrentCell.Item as Row;if(active==null||active==editing)return;if(!ResolveEdits())return;Edit(active);OpenDetails();};grid.SelectionChanged+=(s,e)=>{if(binding)return;var row=grid.SelectedItem as Row;if(row==null&&grid.SelectedCells.Count>0)return;if(row==editing){if(row!=null)OpenDetails();return;}if(!ResolveEdits()){binding=true;grid.SelectedItem=editing;binding=false;return;}Edit(row);if(row!=null)OpenDetails();else ShrinkDetails();};
  MakeDetailsSelectable(detailHost);InitializeTiles();
  grid.PreviewMouseLeftButtonUp+=(s,e)=>{var row=ItemsControl.ContainerFromElement(grid,e.OriginalSource as DependencyObject) as DataGridRow;if(row!=null && row.Item==editing)OpenDetails();};
 }
 void MakeDetailsSelectable(DependencyObject node){
  var panel=node as Panel;if(panel!=null){for(int i=0;i<panel.Children.Count;i++){
   var text=panel.Children[i] as TextBlock;
   if(text!=null){var selectable=new TextBox{IsReadOnly=true,IsReadOnlyCaretVisible=true,TextWrapping=text.TextWrapping,AcceptsReturn=true,Background=Brushes.Transparent,BorderThickness=new Thickness(0),Padding=new Thickness(0),Margin=text.Margin,FontSize=text.FontSize,FontWeight=text.FontWeight,Foreground=Palette.Text,VerticalAlignment=text.VerticalAlignment};
    selectable.SetBinding(TextBox.TextProperty,new Binding("Text"){Source=text,Mode=BindingMode.OneWay});DockPanel.SetDock(selectable,DockPanel.GetDock(text));panel.Children.RemoveAt(i);panel.Children.Insert(i,selectable);
   }else MakeDetailsSelectable(panel.Children[i]);
  }return;}
  var scroll=node as ScrollViewer;if(scroll!=null&&scroll.Content is DependencyObject)MakeDetailsSelectable((DependencyObject)scroll.Content);
  var border=node as Border;if(border!=null&&border.Child!=null)MakeDetailsSelectable(border.Child);
 }
 void AddColumn(DataGrid g,string header,string property,int width){g.Columns.Add(new DataGridTextColumn{Header=header,Binding=new Binding(property){UpdateSourceTrigger=UpdateSourceTrigger.PropertyChanged},Width=width});}
 void OpenDetails(){if(editing==null)return;if(settings.TableOnly){settings.TableOnly=false;settings.FiltersHidden=true;}GrowForDetails();detailsOpen=true;SetPresentation(false);}
 void ShrinkDetails(){detailsOpen=false;SetPresentation(false);RestoreTrackerWidth();}
 void SetPresentation(bool save){filterPanel.Visibility=settings.FiltersHidden||settings.TableOnly?Visibility.Collapsed:Visibility.Visible;bool expanded=detailsOpen&&editing!=null&&!settings.TableOnly;bool rail=!expanded&&editing!=null&&!settings.TableOnly;bool wasExpanded=detailHost.Visibility==Visibility.Visible;detailHost.Visibility=expanded?Visibility.Visible:Visibility.Collapsed;detailRail.Visibility=rail?Visibility.Visible:Visibility.Collapsed;bodySplitter.Visibility=expanded?Visibility.Visible:Visibility.Collapsed;bodyGrid.ColumnDefinitions[1].Width=new GridLength(expanded?8:0);if(expanded&&!wasExpanded){bodyGrid.ColumnDefinitions[0].Width=new GridLength(1,GridUnitType.Star);bodyGrid.ColumnDefinitions[2].Width=new GridLength(2,GridUnitType.Star);}else if(!expanded){bodyGrid.ColumnDefinitions[0].Width=new GridLength(1,GridUnitType.Star);bodyGrid.ColumnDefinitions[2].Width=new GridLength(rail?28:0);}filtersButton.Content=filterPanel.Visibility==Visibility.Visible?"Hide filters":"Show filters";tableButton.Content=tableMode?"Tiles":"Table";RenderTiles(false);if(save){try{Data.Save(settingsPath,settings);}catch(Exception e){status.Text="View changed, but could not remember it: "+e.Message;}}}
 string Pick(MultiFilter c){return c.SelectedItem;} void Replace(MultiFilter c,IEnumerable<string> values){c.Replace(values);} string Pick(ComboBox c){return c.SelectedItem as string??"";}
 void Replace(ComboBox c,IEnumerable<string> values){string old=Pick(c);c.Items.Clear();foreach(var v in values)c.Items.Add(v);c.SelectedItem=c.Items.Contains(old)?old:c.Items[0];}
 void RefreshFilters(){bool previous=ready;ready=false;Replace(category,new[]{"All categories"}.Concat(achievements.Select(x=>x.Category).Distinct().OrderBy(x=>x)));Replace(region,new[]{"All regions"}.Concat(research==null?Enumerable.Empty<string>():joined.SelectMany(x=>x.Candidates).Select(x=>x.Region).Where(x=>!String.IsNullOrWhiteSpace(x)).Distinct().OrderBy(x=>x)));RefreshZones();ready=previous;}
 void RefreshZones(){bool previous=ready;ready=false;var farmsAll=research==null?new List<Farm>():joined.SelectMany(x=>x.Candidates).ToList();var z=farmsAll.Where(f=>region.Matches(f.Region)).SelectMany(f=>(f.Zone??"").Split(new[]{',',';'},StringSplitOptions.RemoveEmptyEntries).Select(part=>Guides.Zone(part.Trim()))).Where(x=>!String.IsNullOrWhiteSpace(x));if(Pick(region)=="Karanas")z=z.Concat(new[]{"North Karana","West Karana","South Karana","East Karana"});Replace(zone,new[]{"All zones","Unresearched"}.Concat(z.Distinct().OrderBy(x=>x)));ready=previous;}
 bool FarmMatch(Farm f){return region.Matches(f.Region)&&((f.Zone??"").Split(new[]{',',';'},StringSplitOptions.RemoveEmptyEntries).Any(z=>zone.Matches(Guides.Zone(z.Trim()))));}
 bool LocationMatch(Row r){if(region.IsAll&&zone.IsAll)return true;if(!zone.IsAll&&zone.Matches("Unresearched")&&r.Candidates.Count==0&&!Guides.NoFixedLocation(r.A))return true;return r.Locations.Any(FarmMatch)||detours.IsChecked==true&&r.Locations.Any(f=>region.Matches(f.Region)&&(f.Via??"").Split(new[]{'>','→'},StringSplitOptions.RemoveEmptyEntries).Any(z=>zone.Matches(Guides.Zone(z.Trim()))));} bool GroupMatch(Row r){string g=Pick(group),c=r.Category.ToUpperInvariant();return g=="ALL"||g=="BANESTRIKE"&&r.Required||g=="UNLOCKS"&&(c.StartsWith("UNTAPPED")||c.EndsWith(": KEYS"))||g=="SLAYER"&&c.StartsWith("SLAYER")||g=="EXPLORATION"&&c.Contains("EXPLORATION")||g=="PROGRESSION"&&c.Contains("PROGRESSION")||g=="SKILLS"&&(c=="GENERAL: SKILLS"||c=="GENERAL: LEVEL")||g=="TRADESKILLS"&&c.StartsWith("TRADESKILL");}
 void Apply(){if(!ready||research==null)return;tileCache.Clear();tileRows.Clear();tileSignatures.Clear();foreach(var row in joined)row.DisplayOverride=matchingOptions.IsChecked==true&&!(region.IsAll&&zone.IsAll)?row.Candidates.Where(FarmMatch).ToList():null;filtered=joined.Where(r=>GroupMatch(r)&&category.Matches(r.Category)&&(Pick(state)=="All states"||r.State==Pick(state))&&(Pick(era)=="All availability"||r.Era==Pick(era))&&(Pick(risk)=="All risks"||r.Risk==Pick(risk))&&LocationMatch(r)&&(Pick(near)=="Any progress"||Pick(near)=="90% or more"&&r.A.Progress>=.9||Pick(near)=="50% or more"&&r.A.Progress>=.5||Pick(near)=="10 or fewer remaining"&&r.A.Remaining.HasValue&&r.A.Remaining<=10)&&Contains(r.R.Class,classFilter.Text)&&Contains(r.R.Race,raceFilter.Text)&&Contains(r.A.Name+" "+r.Category+" "+r.Location+" "+r.Mobs+" "+r.R.Notes+" "+String.Join(" ",r.A.Requirements.Select(x=>x.Text))+" "+String.Join(" ",r.Candidates.Select(x=>x.Mobs)),search.Text)&&(Pick(metaMatch)=="All research"||Pick(metaMatch)=="Missing research"&&!(Data.HasResearch(r.R)||Guides.Catalog.Any(e=>e.Key==r.A.Key))||Pick(metaMatch)=="Has research"&&(Data.HasResearch(r.R)||Guides.Catalog.Any(e=>e.Key==r.A.Key)))).OrderByDescending(r=>r.Era!="Unavailable").ThenByDescending(r=>r.Score).ThenBy(r=>r.A.Name).ToList();
  string key=editing==null?"":editing.A.Key;binding=true;grid.ItemsSource=filtered;grid.SelectedItem=filtered.FirstOrDefault(r=>r.A.Key==key);binding=false;if(!dirty){var selection=grid.SelectedItem as Row;Edit(selection);if(selection==null)detailsOpen=false;}UpdateSummary();SetPresentation(false);
 }
 static bool Contains(string s,string q){return (s??"").IndexOf((q??"").Trim(),StringComparison.OrdinalIgnoreCase)>=0;}
 void UpdateSummary(){var p=achievements.FirstOrDefault(a=>Data.Normalize(a.Name)=="progressive"&&a.Category.StartsWith("Slayer"));var req=p==null?new List<Requirement>():p.Requirements.Where(x=>!x.Optional).ToList();int complete=achievements.Count(a=>a.Complete);var rr=joined.Where(r=>r.Required&&!r.A.Complete).ToList();int tracked=rr.Where(r=>r.A.Remaining.HasValue).Sum(r=>r.A.Remaining.Value);UpdateProgressOverview(p!=null,req.Count(x=>x.Complete),req.Count,complete,achievements.Count,tracked);int missing=req.Count(x=>!joined.Any(r=>r.Required&&Data.Normalize(r.A.Name)==x.Reference));summaryDetails="BANESTRIKE / Progressive: "+(p==null?"Not present":req.Count(x=>x.Complete)+" / "+req.Count+" required complete · "+req.Count(x=>!x.Complete)+" remaining · "+tracked.ToString("N0")+" tracked kills left")+"\nFaction-sensitive: "+rr.Count(r=>r.Risk=="High")+" · Bottlenecks: "+rr.Count(r=>r.R.Bottleneck!="")+" · Unknown remaining counters: "+rr.Count(r=>!r.A.Remaining.HasValue)+"\nIN THIS EXPORT: "+complete+" / "+achievements.Count+" complete · "+(achievements.Count==0?0:(double)complete/achievements.Count).ToString("P1")+" · "+(achievements.Count-complete)+" remaining · "+achievements.Count(a=>!a.Complete&&a.Progress>=.9)+" near complete (90%+)   |   Showing "+filtered.Count+" objectives"+(complete==0?"\nOnly achievements included in this TXT are shown. Export all states/categories for full coverage.":"")+(missing>0?"\n"+missing+" parent reference(s) have no matching achievement header; parent status retained.":"");UpdateFocusLine();}
 void Edit(Row row){binding=true;editing=row;RefreshMobNames();editFarms.Clear();if(row==null){detailTitle.Text="Select an achievement";requirements.Text="";completionGuide.Text="";basis.Text=why.Text="";personalNotes.Text=notes.Text=sources.Text=bottleneck.Text=classEdit.Text=raceEdit.Text="";binding=false;dirty=false;return;}completionGuide.Text=row.R.Cleaned?CleanResearch.Guide(row):Guides.Text(row,achievements);var r=row.R;detailTitle.Text=row.A.Name;basis.Text=row.Category+" · "+row.State+" · "+row.A.Basis;why.Text="Priority: "+row.Why;requirements.Text=String.Join("\n",row.A.Requirements.Select(x=>(x.Complete?"[Complete] ":"[Incomplete] ")+x.Text.Replace('\t',' ')));foreach(var f in row.Candidates)editFarms.Add(new Farm{PortRoute=TravelGuide.ForFarm(f),Zone=f.Zone,Region=f.Region,Mobs=f.Mobs,Portal=f.Portal,Via=f.Via,Evidence=f.Evidence,Faction=f.Faction,Kind=f.Kind,Selected=row.Preferred.Any(p=>p.Zone==f.Zone&&p.Mobs==f.Mobs)});if(!tierEdit.Items.Contains(r.Tier))tierEdit.Items.Add(r.Tier);if(!eraEdit.Items.Contains(r.Era))eraEdit.Items.Add(r.Era);tierEdit.SelectedItem=r.Tier;riskEdit.SelectedItem=r.Risk;eraEdit.SelectedItem=r.Era;difficulty.SelectedItem=r.Difficulty.ToString();travel.SelectedItem=r.Travel.ToString();personalNotes.Text=ProfileNotes(r);notes.Text=r.Notes;sources.Text=r.Sources;bottleneck.Text=r.Bottleneck;classEdit.Text=r.Class;raceEdit.Text=r.Race;dirty=false;editBaseline=EditorState();binding=false;}
 bool SaveResearch(){if(editing==null)return true;try{farms.CommitEdit(DataGridEditingUnit.Cell,true);farms.CommitEdit(DataGridEditingUnit.Row,true);var list=editFarms.ToList();if(list.Count(f=>f.Selected&&f.Kind!="Required stop")>1)throw new Exception("Choose only one preferred zone option for the table.");if(list.Any(f=>String.IsNullOrWhiteSpace(f.Zone)))throw new Exception("Each farming row needs a Zone. Delete unused rows.");var r=new Research{Cleaned=editing.R.Cleaned,RequiredFaction=editing.R.RequiredFaction,FactionHit=editing.R.FactionHit,Verification=editing.R.Verification,ResearchHistory=editing.R.ResearchHistory,Key=editing.A.Key,Name=editing.A.Name,Category=editing.A.Category,Farms=list,Risk=Pick(riskEdit),Era=Pick(eraEdit),Tier=Pick(tierEdit),Difficulty=Int32.Parse(Pick(difficulty)),Travel=Int32.Parse(Pick(travel)),Notes=notes.Text,PersonalNotes=personalNotes.Text,Sources=sources.Text,Bottleneck=bottleneck.Text,Class=classEdit.Text,Race=raceEdit.Text};var copy=Data.Json().Deserialize<ResearchFile>(Data.Json().Serialize(research));copy.Items.RemoveAll(x=>x.Key==r.Key);copy.Items.Add(r);SaveProfileNotes(r.Key,personalNotes.Text);if(ActiveProfile!=null)r.PersonalNotes="";Data.Save(researchPath,copy);research=copy;dirty=false;joined=Data.Join(achievements,research);RefreshFilters();Apply();status.Text="Research saved with a dated backup. Last TXT refresh: "+lastSuccess;return true;}catch(Exception e){MessageBox.Show(this,e.Message,"Could not save research");return false;}}
 string EditorState(){return Data.Json().Serialize(new{Farms=editFarms.ToList(),Tier=Pick(tierEdit),Risk=Pick(riskEdit),Era=Pick(eraEdit),Difficulty=Pick(difficulty),Travel=Pick(travel),Notes=notes.Text,PersonalNotes=personalNotes.Text,Sources=sources.Text,Bottleneck=bottleneck.Text,Class=classEdit.Text,Race=raceEdit.Text});} bool HasActualEdits(){return editing!=null&&EditorState()!=editBaseline;} bool ResolveEdits(){farms.CommitEdit(DataGridEditingUnit.Cell,true);farms.CommitEdit(DataGridEditingUnit.Row,true);dirty=HasActualEdits();if(!dirty)return true;var answer=MessageBox.Show(this,"Save your research edits before continuing?","Unsaved research",MessageBoxButton.YesNoCancel);if(answer==MessageBoxResult.Cancel)return false;if(answer==MessageBoxResult.Yes)return SaveResearch();dirty=false;return true;}
 void Browse(){if(!ResolveEdits())return;var dialog=new OpenFileDialog{Title="Select your achievement export",Filter="Achievement exports (*.txt)|*.txt|All files (*.*)|*.*",FileName=source.Text};if(dialog.ShowDialog(this)==true){source.Text=dialog.FileName;LoadSource(true);}}
 string Hash(string text){using(var sha=SHA256.Create())return Convert.ToBase64String(sha.ComputeHash(Encoding.UTF8.GetBytes(text)));}
 void LoadSource(bool manual){try{string path=manual?source.Text.Trim():settings.SourcePath;if(manual&&ready&&File.Exists(path)&&SelectManualProfile(path))return;if(String.IsNullOrWhiteSpace(path)){status.Text="Choose your achievement TXT with Browse to begin. Your progress and personal notes stay on this computer.";return;}if(!File.Exists(path))throw new Exception("Achievement file not found. Choose the TXT with Browse.");string a=File.ReadAllText(path);System.Threading.Thread.Sleep(100);string b=File.ReadAllText(path);if(a!=b)throw new Exception("Export is still changing. Waiting for a stable file.");var parsed=Data.Parse(b);if(research==null){research=Data.Seed(parsed);Data.ApplyResearchUpdates(parsed,research);Data.Save(researchPath,research);}else{var next=Data.Json().Deserialize<ResearchFile>(Data.Json().Serialize(research));if(Data.ApplyResearchUpdates(parsed,next)){Data.Save(researchPath,next);research=next;}}Data.Atomic(ExportSnapshotPath(),b);settings.SourcePath=Path.GetFullPath(path);Data.Save(settingsPath,settings);CaptureTileOrder();ExportProgress(achievements,parsed);achievements=parsed;loadedHash=Hash(b);loadedExportStamp=File.GetLastWriteTimeUtc(path).Ticks;lastSuccess=DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");joined=Data.Join(achievements,research);batchRefresh=true;RefreshFilters();Apply();batchRefresh=false;RenderTiles(true);if(exportAdvanced&&settings.RecentFirst)tileScroll.ScrollToTop();status.Text="Loaded "+parsed.Count+" achievements · Last successful refresh "+lastSuccess+" · Watching "+settings.SourcePath+" · TXT is read-only";}catch(Exception e){batchRefresh=false;status.Text="Refresh failed: "+e.Message+"  Last success: "+lastSuccess+". Previous data retained.";if(achievements.Count==0 && File.Exists(ExportSnapshotPath())){try{achievements=Data.Parse(File.ReadAllText(ExportSnapshotPath()));if(research!=null){joined=Data.Join(achievements,research);RefreshFilters();Apply();status.Text+=" Showing saved snapshot (not current).";}}catch{}}}}
 void Poll(){if(live!=null)liveState.Text=live.Status;if(closing||String.IsNullOrWhiteSpace(settings.SourcePath))return;try{if(File.GetLastWriteTimeUtc(settings.SourcePath).Ticks==loadedExportStamp)return;string content=File.ReadAllText(settings.SourcePath),hash=Hash(content);if(hash==loadedHash&&File.GetLastWriteTimeUtc(settings.SourcePath).Ticks==loadedExportStamp)return;if(hash!=candidateHash){candidateHash=hash;return;}LoadSource(false);}catch(Exception e){status.Text="File monitoring: "+e.Message+" · Last success "+lastSuccess+". Previous data retained.";}}
 void Reset(){ready=false;group.SelectedItem="ALL";category.SelectedIndex=0;state.SelectedItem="Incomplete";near.SelectedIndex=0;era.SelectedIndex=0;risk.SelectedIndex=0;region.SelectedIndex=0;search.Text=classFilter.Text=raceFilter.Text="";metaMatch.SelectedIndex=0;matchingOptions.IsChecked=false;detours.IsChecked=false;ready=true;RefreshZones();zone.SelectedIndex=0;Apply();}
 void ShowRoutes(){var groups=filtered.SelectMany(r=>r.Locations.Select(f=>new{Row=r,Farm=f})).GroupBy(x=>x.Farm.Zone).OrderByDescending(g=>g.Select(x=>x.Row.A.Key).Distinct().Count());var sb=new StringBuilder("FARMING DESTINATIONS IN THE CURRENT VIEW\nCounts are objectives, not guaranteed shared kill credit.\n\n");foreach(var g in groups){sb.AppendLine(g.Key+" — "+g.Select(x=>x.Row.A.Key).Distinct().Count()+" objective(s)");foreach(var x in g)sb.AppendLine("  "+x.Row.A.Name+" · "+x.Row.Remaining+" left · "+x.Farm.Mobs+"\n  "+TravelGuide.ForFarm(x.Farm)+"\n  Evidence: "+x.Farm.Evidence+"\n  Faction: "+x.Farm.Faction);sb.AppendLine();}ShowText("Route summary",sb.ToString());}
 void ShowText(string title,string text){var w=new Window{Owner=this,Title=title,Width=850,Height=650,Content=new TextBox{Text=text,IsReadOnly=true,TextWrapping=TextWrapping.Wrap,AcceptsReturn=true,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Margin=new Thickness(14),Padding=new Thickness(8)}};w.ShowDialog();}
 void Guide(){string pdf=Path.Combine(Home,"docs","EQ Legends Achievement Companion - Easy Guide.pdf");if(File.Exists(pdf)){System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(pdf){UseShellExecute=true});return;}ShowText("Using EQ Legends Achievement Companion",File.ReadAllText(Path.Combine(Home,"README.txt"))+"\n\nCATEGORY BREAKDOWN\n"+String.Join("\n",achievements.GroupBy(x=>x.Category).OrderBy(x=>x.Key).Select(g=>g.Key+": "+g.Count(a=>a.Complete)+" / "+g.Count()+" complete")));}
 void Export(){var d=new SaveFileDialog{Filter="CSV file|*.csv",FileName="Legends-achievements.csv"};if(d.ShowDialog(this)!=true)return;try{var sb=new StringBuilder("Achievement,Destination / Farming Zone,Mobs / Item Source & Turn-In,Remaining,Progress,Required Faction,Port Ins & Routes,Faction Hit,Action Tier,Still to Verify,Availability,Category,State\r\n");foreach(var r in filtered)sb.AppendLine(String.Join(",",new[]{r.Achievement,r.Location,r.Mobs,r.Remaining,r.Progress,r.CampFaction,r.PortsAndRoute,r.R.FactionHit??"",r.Tier,r.ResearchGaps,r.Era,r.Category,r.State}.Select(x=>"\""+x.Replace("\"","\"\"")+"\"")));File.WriteAllText(d.FileName,sb.ToString(),new UTF8Encoding(true));status.Text="Exported "+filtered.Count+" visible rows.";}catch(Exception e){MessageBox.Show(this,e.Message,"Export failed");}}
 public void IntegrationTests(string fixture){
  if(achievements.Count!=3)throw new Exception("Native initial import failed");Edit(joined.First());UpdateLayout();dirty=true;if(HasActualEdits()||!ResolveEdits())throw new Exception("Viewing unchanged research caused unsaved edits");var beforeNote=personalNotes.Text;personalNotes.Text="Changed regression note";if(!HasActualEdits())throw new Exception("Actual personal edit was missed");personalNotes.Text=beforeNote;if(HasActualEdits())throw new Exception("Reverted edit remains dirty");dirty=false;Edit(null);
  if(grid.SelectedItem!=null || detailHost.Visibility!=Visibility.Collapsed)throw new Exception("Details must start closed");grid.SelectedItem=filtered.First();if(detailHost.Visibility!=Visibility.Visible)throw new Exception("Selection must open details");ShrinkDetails();Apply();if(detailHost.Visibility!=Visibility.Collapsed)throw new Exception("Refresh reopened details");OpenDetails();if(detailHost.Visibility!=Visibility.Visible)throw new Exception("Reopen failed");settings.TableOnly=true;SetPresentation(false);if(filterPanel.Visibility!=Visibility.Collapsed || detailHost.Visibility!=Visibility.Collapsed)throw new Exception("Table only failed");settings.TableOnly=false;ShrinkDetails();
  string bytes=File.ReadAllText(researchPath);File.WriteAllText(fixture,File.ReadAllText(fixture).Replace("9/10","8/10"));Poll();Poll();
  if(achievements[1].Remaining!=2 || File.ReadAllText(researchPath)!=bytes)throw new Exception("Automatic refresh / research preservation failed");
  var target=joined.First(r=>r.A.Name=="Tiny Foe");Edit(target);notes.Text="Native saved note";personalNotes.Text="My private farming reminder";editFarms.Add(new Farm{Zone="North Karana",Region="Karanas",Mobs="Test only",Selected=true});if(!SaveResearch())throw new Exception("Native save failed");
  if(Data.Load<ResearchFile>(researchPath).Items.First(x=>x.Key==target.A.Key).PersonalNotes!="My private farming reminder")throw new Exception("Personal note not saved");search.Text="My private farming reminder";Apply();if(filtered.Count!=0)throw new Exception("Personal note leaked into search");search.Text="";
  region.SelectedItem="Karanas";Apply();if(filtered.Count!=1)throw new Exception("Region filter failed");zone.SelectedItem="North Karana";Apply();if(filtered.Count!=1)throw new Exception("Mob filter failed");
  string valid=File.ReadAllText(fixture);File.WriteAllText(fixture,"");Poll();Poll();if(achievements.Count!=3 || !status.Text.Contains("failed"))throw new Exception("Invalid refresh did not retain snapshot");
  File.WriteAllText(fixture,valid);string second=fixture+".second.txt";File.WriteAllText(second,valid.Replace("8/10","7/10"));source.Text=second;LoadSource(true);if(Data.Load<Settings>(settingsPath).SourcePath!=second || achievements[1].Remaining!=3)throw new Exception("File location persistence failed");
  if(Data.Load<ResearchFile>(researchPath).Items.First(x=>x.Key==target.A.Key).Notes!="Native saved note")throw new Exception("File change lost research");
  Reset();Edit(joined.First(r=>r.A.Name=="Tiny Foe"));editFarms.Add(new Farm{Zone="Lesser Faydark",Region="Faydwer",Mobs="Alternative test mobs"});if(!SaveResearch())throw new Exception("Alternative save failed");var preferenceBytes=File.ReadAllText(researchPath);
  region.SetChoices("Faydwer");Apply();if(filtered.Count!=0)throw new Exception("Preferred-only filter included unselected alternative");matchingOptions.IsChecked=true;Apply();if(filtered.Count!=1||filtered[0].Location!="Lesser Faydark")throw new Exception("Matching override did not show alternative");
  region.SetChoices("Faydwer","Karanas");Apply();if(filtered.Count!=1||!filtered[0].Location.Contains("North Karana")||!filtered[0].Location.Contains("Lesser Faydark"))throw new Exception("Multiple regions did not combine alternatives");matchingOptions.IsChecked=false;Apply();if(filtered.Count!=1||filtered[0].Location!="North Karana"||File.ReadAllText(researchPath)!=preferenceBytes)throw new Exception("Filter override changed saved preferences");
  category.SetChoices("Slayer: Skill","Slayer: General");Apply();if(filtered.Count!=1)throw new Exception("Multiple categories failed");zone.SetChoices();Apply();if(filtered.Count!=0)throw new Exception("Clear filter should match nothing");zone.SelectedIndex=0;Apply();if(filtered.Count!=1)throw new Exception("Select all failed");Reset();
 }
 public void CheckPortableStart(){if(source.Text!=""||achievements.Count!=0||detailsOpen||!status.Text.StartsWith("Choose your"))throw new Exception("Portable first-run setup failed");}
 public void Preview(string path){region.SelectedItem="Karanas";Apply();UpdateLayout();Measure(new Size(1420,920));Arrange(new Rect(0,0,1420,920));UpdateLayout();var image=new RenderTargetBitmap(1420,920,96,96,PixelFormats.Pbgra32);image.Render((Visual)Content);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(image));using(var stream=File.Create(path))encoder.Save(stream);}
}
public static class Program {
 [STAThread] public static void Main(string[] args){try{if(args.Length>0&&args[0]=="--apply-update"){Environment.ExitCode=CompanionUpdater.Apply(args);return;}if(args.Contains("--test")){Tests.Run();return;}var app=new Application();var window=new MainWindow();if(args.Contains("--preview")){window.Show();window.Preview(Path.Combine(MainWindow.Home,"preview.png"));window.Close();return;}app.Run(window);}catch(Exception e){File.WriteAllText(Path.Combine(MainWindow.Home,"error.log"),e.ToString());if(!args.Contains("--test"))MessageBox.Show(e.Message,"EQ Legends Achievement Companion");Environment.ExitCode=1;}}
}
}
