using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
namespace LegendsCompanion {
public static class Tests {
 static void LiveTests(){LiveMonitor.CheckPopupIndependence();
  var kerra=Data.Parse("Slayer: Skill\nI\tNot a Kerran the World!\nI\t\tKerrans\t5/100\nSlayer: Conquest\nI\tCatnipped In the Bud\nI\t\tKerrans and Vah Shir.\t5/1000\n");
  foreach(string mob in new[]{"a kerran `amir","a kerran mujahed","a kerran pasdar","Kerran tiger spahi"}){var k=new KillProgress();Assert(k.Process("You have slain "+mob+"!",kerra,new List<MobMatch>()).Count==2,"Kerran race variants");k.Process("Jebanab told you, 'Attacking "+mob+" Master.'",kerra,new List<MobMatch>());Assert(k.Process(mob+" has been slain by Jebanab!",kerra,new List<MobMatch>()).Count==2,"Kerran pet variants");}
  Assert(new KillProgress().Process("You have slain a kerran puma!",kerra,new List<MobMatch>()).Count==0,"Kerran animals not guessed");
  var clockworks=Data.Parse("Slayer: Skill\nI\tGnome Tested, Steamwork Approved!\nI\t\tClockwork: Beetles, Boars, Dragons, Rats, Snakes, Spiders, Gnomeworks, Copters, and Tin Soldiers.\t81/100\n");
  var clockEngine=new KillProgress();
  foreach(string mob in new[]{"a clockwork spider","A Clockwork Spider","a clock work spider","a clockwork rat","rebel clockwork","rogue clockwork","giant clockwork spider"})Assert(clockEngine.Process("You have slain "+mob+"!",clockworks,new List<MobMatch>()).Count==1,"clockwork variant: "+mob);
  foreach(string mob in new[]{"a spider","a rat","a clockwork spider pet"})Assert(clockEngine.Process("You have slain "+mob+"!",clockworks,new List<MobMatch>()).Count==0,"unqualified clockwork target: "+mob);
  clockEngine.Process("Zobtik told you, 'Attacking a clockwork spider Master.'",clockworks,new List<MobMatch>());
  Assert(clockEngine.Process("A clockwork spider has been slain by Zobtik!",clockworks,new List<MobMatch>()).Count==1,"pet clockwork spider");
  var families=Data.Parse("Slayer: Skill\nI\tFor the Hive!\nI\t\tBixies\t52/100\nI\tAmazing!\nI\t\tMinotaurs and Tizmak.\t18/100\nI\tSpin Me Right Round\nI\t\tDervishes\t42/100\n");
  var brownies=Data.Parse("Slayer: Conquest\nI\tShorter People\nI\t\tBixies, Brownies, Dryads, Fairies, and Pixies.\t217/1000\nSlayer: Skill\nI\tJumjummery\nI\t\tBrownies\t7/100\n");
  var brownieEngine=new KillProgress();
  foreach(string brownie in new[]{"a mountain brownie","brownie scout"}){
   var updates=brownieEngine.Process("You have slain "+brownie+"!",brownies,new List<MobMatch>());
   Assert(updates.Count==2&&updates.Any(n=>n.Name=="Shorter People"),"brownie variant advances all matching achievements");
  }
  var kobolds=Data.Parse("Slayer: Conquest\nI\tKobolded Killer\nI\t\tKobolds\t528/1000\nSlayer: General\nI\tMore Kobolds\nI\t\tKobolds\t528/5000\n");
  var koboldEngine=new KillProgress();
  foreach(string mob in new[]{"a kobold runt","a kobold scout","a kobold shaman","a kobold missionary","a kobold","a burly kobold","a greater kobold","a greater kobold shaman","a kobold hunter","a kobold king","a kobold noble","a kobold priest","a kobold champion","kobold predator"})
   Assert(koboldEngine.Process("You have slain "+mob+"!",kobolds,new List<MobMatch>()).Count==2,"kobold variant advances matching achievements: "+mob);
  Assert(koboldEngine.Process("You have slain a greater kobold shaman pet!",kobolds,new List<MobMatch>()).Count==0,"unverified pet credit not assumed");
  var petEngine=new KillProgress();
  petEngine.Process("Jabekab told you, 'Attacking a minotaur slaver Master.'",families,new List<MobMatch>());
  Assert(petEngine.Process("A minotaur slaver has been slain by Jabekab!",families,new List<MobMatch>()).Single().Name=="Amazing!","own pet credited");
  Assert(petEngine.Process("A minotaur slaver has been slain by Otherpet!",families,new List<MobMatch>()).Count==0,"other pet ignored");
  petEngine.Process("Newpet told you, 'Attacking Minotaur Guard Master.'",families,new List<MobMatch>());
  Assert(petEngine.Process("Minotaur Guard has been slain by Newpet!",families,new List<MobMatch>()).Count==1,"new summoned pet recognized");
  Assert(petEngine.Process("Minotaur Guard has been slain by Jabekab!",families,new List<MobMatch>()).Count==0,"old pet superseded");
  petEngine.Reset();Assert(petEngine.Process("Minotaur Guard has been slain by Newpet!",families,new List<MobMatch>()).Count==0,"ownership clears on log reset");
  var familyEngine=new KillProgress();
  foreach(string mob in new[]{"a bixie","a bixie drone","a minotaur slaver","Minotaur Guard","Minotaur Lord","a rock dervish"}){
   var notice=familyEngine.Process("[Sun Sep 13 19:13:23 2026] You have slain "+mob+"!",families,new List<MobMatch>());
   Assert(notice.Count==1,"observed creature variant matched: "+mob);
   Assert(notice[0].Name==(mob.ToLowerInvariant().Contains("bixie")?"For the Hive!":mob.Contains("dervish")?"Spin Me Right Round":"Amazing!"),"correct achievement for "+mob);
  }
  var all=Data.Parse("Slayer: Skill\nI\tBones\nI\t\tSkeletons.\t9/100\nI\tPeople\nI\t\tHumans.\t2/100\n");var engine=new KillProgress();var maps=new List<MobMatch>();
  Assert(engine.Process("[Sat Sep 12 12:00:00 2026] You have slain a skeleton!",all,maps).Count==1,"own exact mob kill matched");
  Assert(all[0].Requirements[0].Current==9,"live estimates never modify export counters");
  Assert(engine.Process("A skeleton has been slain by Someone!",all,maps).Count==0,"other players kills ignored");
  Assert(engine.Process("Someone tells you, 'You have slain a skeleton!'",all,maps).Count==0,"chat is not a kill event");
  Assert(engine.Process("You have slain a bandit!",all,maps).Count==0,"ambiguous bandit race not guessed");
  maps.Add(new MobMatch{Mob="a test human",Achievement="People"});Assert(engine.Process("You have slain a test human!",all,maps).Count==1,"explicit user match supported");
  Assert(engine.Process("Your guildmate Bob has completed Bones achievement.",all,maps).Count==0,"guildmate completion ignored");
  Assert(engine.Process("You have completed achievement: Bones",all,maps).Single().Complete,"native personal completion confirmed");
  Assert(engine.Process("You have completed achievement: Bones",all,maps).Count==0,"duplicate completion suppressed");
  Assert(engine.Process("You have slain a skeleton!",all,maps).Count==0,"completed achievement stops estimates");engine.Reset();
  Assert(engine.Process("You have slain a skeleton!",all,maps).Single().Detail.Contains("+1 estimated"),"export reset clears session counts");
  string folder=Path.Combine(MainWindow.Home,"test-output");Directory.CreateDirectory(folder);string file=Path.Combine(folder,"live-tail-fixture.txt");File.WriteAllText(file,"old kill\n");var tail=new LogTail(file);Assert(tail.Read().Count==0,"log attaches at EOF without replay");File.AppendAllText(file,"You have slain a ske");Assert(tail.Read().Count==0,"partial log line buffered");File.AppendAllText(file,"leton!\r\n");Assert(tail.Read().Single()=="You have slain a skeleton!","partial lines reassembled exactly once");Assert(tail.Read().Count==0,"unchanged log not replayed");File.WriteAllText(file,"reset\n");Assert(tail.Read().Count==0,"truncated log resets without replay");File.AppendAllText(file,"new\n");Assert(tail.Read().Single()=="new","tail resumes after truncate");File.Delete(file);Assert(tail.Read().Count==0,"missing log tolerated");File.WriteAllText(file,"replacement\n");Assert(tail.Read().Count==0,"replacement attaches without history");File.AppendAllText(file,"after\n");Assert(tail.Read().Single()=="after","replacement new events read");File.Delete(file);
 }
 static int passed=0;static void Assert(bool value,string message){if(!value)throw new Exception("TEST FAILED: "+message);passed++;}
 public static void Run(){LiveTests();
  string sample="Slayer: General\nI\tProgressive\nI\t\tComplete the achievement \"Tiny foe!\"\nI\t\t(Optional) Complete the achievement \"Rare foe\"\nSlayer: Skill\nI\tTiny Foe\nI\t\tRats\t9/10\nI\tRare foe\nI\t\tRare\t0/100\n";
  var pickA=new Farm{Zone="West Karana",Mobs="High Elf bandits",Selected=true};var pickB=new Farm{Zone="Greater Faydark",Mobs="Other candidate"};var pickRow=new Row{A=new Achievement{Category="Slayer: Skill",Name="Example"},R=new Research{Farms=new List<Farm>{pickA,pickB}}};Assert(pickRow.Location=="West Karana"&&pickRow.Mobs=="High Elf bandits","only selected zone and mob list appear in table");pickA.Selected=false;pickB.Selected=true;Assert(pickRow.Location=="Greater Faydark"&&pickRow.R.Farms.Count==2,"changing preferred zone retains alternatives");var restored=Data.Json().Deserialize<Research>(Data.Json().Serialize(pickRow.R));Assert(restored.Farms[1].Selected&&!restored.Farms[0].Selected,"preferred zone persists");pickB.Selected=false;Assert(pickRow.Location=="West Karana","first option is the default when no preference exists");
  Assert(TravelGuide.ForZone("West Karana").Contains("Wizard: West Karana Portal — West Karana"),"Wizard uses direct West Karana port");Assert(TravelGuide.ForZone("West Karana").Contains("North Karana → West Karana"),"Druid has onward Karana route");Assert(TravelGuide.ForZone("Plane of Sky").Contains("Druid: East Commons portal → East Freeport → click the orb → Plane of Sky"),"Sky route uses corrected Druid arrival and Freeport orb");Assert(TravelGuide.ForZone("Lesser Faydark").Contains("Circle of Steamfont"),"Druid uses adjacent Steamfont port");Assert(TravelGuide.ForFarm(new Farm{Zone="West Karana",PortRoute="My reviewed route"})=="My reviewed route","saved route override preserved");Assert(TravelGuide.ForZone("Unknown test zone").Contains("Route not yet verified"),"unverified destination is not invented");
  var matchAll=Data.Parse("Slayer: Skill\nI\tTest rats\nI\t\tRats\t0/10\nSlayer: Conquest\nI\tTest vermin\nI\t\tRats, Bats\t0/100\n");var matchFile=new ResearchFile();matchFile.Items.Add(new Research{Key=matchAll[0].Key,Farms=new List<Farm>{new Farm{Zone="Test zone",Mobs="Rats"}}});Assert(Guides.SlayerAlternatives(matchAll[1],matchAll,matchFile).Count==1,"broader target group inherits documented candidate");matchAll[1].Requirements[0].Text="Bats";Assert(Guides.SlayerAlternatives(matchAll[1],matchAll,matchFile).Count==0,"unrelated target group does not inherit mobs");
  var personalOnly=new Research{PersonalNotes="Remember my route"};Assert(!Data.HasResearch(personalOnly),"personal notes do not alter research filter");
  var a=Data.Parse(sample);Assert(a.Count==3,"parse all achievement headers");Assert(a[1].Remaining==1,"counter remaining");Assert(Math.Abs(a[1].Progress-.9)<.001,"percentage");
  var research=new ResearchFile();research.Items.Add(new Research{Key=a[1].Key,Name=a[1].Name,Category=a[1].Category,Notes="Keep me",Farms=new List<Farm>{new Farm{Zone="North Karana",Region="Karanas"}}});
  var rows=Data.Join(a,research);Assert(rows[1].Required && !rows[2].Required && rows[2].Optional,"optional requirements excluded");Assert(rows[1].R.Notes=="Keep me","research join");
  var updated=Data.Parse(sample.Replace("Tiny Foe","TINY FOE!").Replace("9/10","10/10"));var again=Data.Join(updated,research);Assert(again[1].R.Notes=="Keep me","normalized punctuation/case preserves notes");Assert(again[1].A.Remaining==0,"changed source updates counters");Assert(!again[1].A.Complete,"counter never overrides incomplete header");
  string newSource=sample+"New Era: New Category\nI\tNew Achievement\nI\t\tDo something\n";Assert(Data.Parse(newSource).Count==4,"new category imports");
  foreach(string bad in new[]{"", "Slayer: Skill\nI\tCut off",sample+"Slayer: Skill\nI\tTiny Foe!\nI\t\tRats\t9/10"}){bool failed=false;try{Data.Parse(bad);}catch{failed=true;}Assert(failed,"reject malformed or duplicate snapshot");}
  var actual=Data.Parse(File.ReadAllText(Path.Combine(MainWindow.Home,"tests","fixtures","achievements.txt")));var seeded=Data.Seed(actual);var live=Data.Join(actual,seeded);Assert(actual.Count>0,"current export imports without assuming a fixed count");Assert(Data.Seed(Data.Parse("Slayer: Skill\nI\tYou're Not Scaring Anyone\nI\t\tScarecrows\t0/50\n")).Items.Any(x=>x.Farms.Any(f=>f.Zone=="West Karana")),"Karana research seeded from stable fixture");Assert(live.Where(x=>x.Required&&!x.A.Complete).All(x=>x.A.Remaining.HasValue),"required kill counters covered");
  Guides.Load(MainWindow.Home);Assert(Guides.Catalog.Count>=108,"expanded guide catalog loaded");
  var traveler=Data.Parse("EverQuest: Exploration\nI\tThe Western Plains of Karana Traveler\nI\t\tVisit The Western Plains of Karana\n")[0];var tr=Data.Join(new List<Achievement>{traveler},new ResearchFile())[0];Assert(tr.Candidates[0].Zone=="West Karana"&&tr.Location=="West Karana","derived destination has a useful default");Assert(tr.R.Farms.Count==0,"derived destinations do not overwrite saved farms");
  var level=Data.Parse("General: Level\nI\tLevel 50\nI\t\tReach Level 50\n")[0];Assert(new Row{A=level,R=new Research()}.Location=="No fixed location","level objective not misreported as missing mob research");Assert(new Settings().SourcePath=="","guild setup has no personal path");
  foreach(var objective in actual){var row=new Row{A=objective,R=new Research()};Assert(!String.IsNullOrWhiteSpace(Guides.Text(row,actual)),"guidance exists for current objective");}
  Guides.Load(MainWindow.Home);
  var coverageRows=Data.Join(actual,Data.Load<ResearchFile>(Path.Combine(MainWindow.Home,"data","research.json")));
  Assert(coverageRows.All(r=>Guides.NoFixedLocation(r.A)||r.Candidates.Count>0||((r.A.Key=="slayerskill|woodyoucouldyou"||r.A.Key=="slayerskill|highlyuncivilized")&&r.R.Notes.Contains("withdrawn"))),"all current objectives have a destination or a no-fixed-location explanation: "+String.Join(", ",coverageRows.Where(r=>!Guides.NoFixedLocation(r.A)&&r.Candidates.Count==0).Select(r=>r.A.Name)));
  var dark=coverageRows.First(r=>r.A.Name=="Dark Ones");Assert(dark.Mobs.Contains("Bregna")&&dark.Mobs.Contains("Grobb")&&dark.Mobs.Contains("Belts"),"Dark Ones shows item source and turn-in");
  var sash=coverageRows.First(r=>r.A.Name=="Knights of Thunder");Assert(sash.Location=="West Karana"&&sash.Mobs.Contains("Chesgard")&&sash.Mobs.Contains("South Qeynos"),"item option filters on farm zone and displays turn-in zone");
  var iksar=coverageRows.First(r=>r.A.Name=="Race Unlock - Iksar");Assert(iksar.Mobs.Contains("Iktra"),"Iksar faction spelling resolves to its method");
  var halfElf=coverageRows.First(r=>r.A.Name=="Race Unlock - Half Elf");Assert(halfElf.Location=="No fixed location"&&Guides.Text(halfElf,actual).Contains("Human OR Wood Elf"),"Half Elf explains alternative automatic unlocks");
  Assert(TravelGuide.HasRoute("North Kaladim")&&TravelGuide.HasRoute("Southern Felwithe")&&TravelGuide.HasRoute("Neriak Third Gate"),"new city districts have port routes");
  var missing=new Row{A=new Achievement{Category="Test",Name="No data"},R=new Research()};Assert(missing.PortsAndRoute=="No researched destination yet","empty options never ask user to choose a destination");
  var dir=Path.Combine(MainWindow.Home,"test-output");Directory.CreateDirectory(dir);var path=Path.Combine(dir,"research.json");Data.Save(path,research);var bytes=File.ReadAllText(path);Data.Join(updated,Data.Load<ResearchFile>(path));Assert(File.ReadAllText(path)==bytes,"refresh never writes research");research.Items[0].Notes="Edited";Data.Save(path,research);Assert(Directory.GetFiles(Path.Combine(dir,"backups")).Length>0,"atomic research save makes backup");Assert(Data.Load<ResearchFile>(path).Items[0].Notes=="Edited","saved research reloads");
  string originalHome=MainWindow.Home;var integration=Path.Combine(dir,"native-"+DateTime.Now.ToString("yyyyMMddHHmmssfff"));Directory.CreateDirectory(Path.Combine(integration,"data"));string fixture=Path.Combine(integration,"fixture.txt");File.WriteAllText(fixture,sample);Data.Save(Path.Combine(integration,"data","settings.json"),new Settings{SourcePath=fixture});MainWindow.Home=integration;var window=new MainWindow();window.IntegrationTests(fixture);window.TrackerChecks();window.Close();MainWindow.Home=originalHome;
  var multiple=new Row{A=traveler,R=new Research{Farms=new List<Farm>{new Farm{Zone="Lesser Faydark, Rathe Mountains",Mobs="Drakes",Selected=true}}}};Assert(multiple.Locations.Count==2&&multiple.Locations[1].Zone=="Rathe Mountains","multi-zone saved entry remains independently filterable");
  var portable=Path.Combine(integration,"portable");Directory.CreateDirectory(portable);MainWindow.Home=portable;var blank=new MainWindow();blank.CheckPortableStart();blank.Close();MainWindow.Home=originalHome;
    Guides.Load(originalHome);var completeResearch=Data.Load<ResearchFile>(Path.Combine(originalHome,"data","research.json"));var audited=Data.Join(actual,completeResearch);var audit=new System.Text.StringBuilder("# Research audit\n\nThis report describes the current export, not all achievements that may exist in game. A source-listed destination is not proof of availability or counter credit.\n\n");foreach(var bucket in audited.GroupBy(r=>r.Category)){audit.AppendLine("## "+bucket.Key+"\n");audit.AppendLine(bucket.Count()+" objectives; "+bucket.Count(r=>r.Risk=="Unknown")+" general faction risks still unknown; "+bucket.Count(r=>r.Era=="Unknown")+" availability fields still unknown; "+bucket.Count(r=>r.Locations.Count>0&&r.Locations.All(f=>TravelGuide.HasRoute(f.Zone)))+" with both class routes in reviewed graph.\n");foreach(var row in bucket)audit.AppendLine("- "+row.Achievement+": "+row.ResearchGaps);audit.AppendLine();}File.WriteAllText(Path.Combine(originalHome,"RESEARCH-AUDIT.md"),audit.ToString());var qa=Path.Combine(integration,"qa");Directory.CreateDirectory(Path.Combine(qa,"data"));File.Copy(Path.Combine(originalHome,"data","guides.json"),Path.Combine(qa,"data","guides.json"));Data.Save(Path.Combine(qa,"data","settings.json"),new Settings{SourcePath=Path.Combine(MainWindow.Home,"tests","fixtures","achievements.txt")});MainWindow.Home=qa;var preview=new MainWindow{ShowActivated=false,Left=-20000,Top=-20000};preview.Show();preview.Preview(Path.Combine(dir,"expanded-preview.png"));preview.Close();MainWindow.Home=originalHome;
  File.WriteAllText(Path.Combine(MainWindow.Home,"test-results.txt"),passed+" data checks passed; Native integration, tile sorting/filter/editor/layout and portable first-run checks passed.\r\nLive export: "+actual.Count+" achievements; "+actual.Count(x=>x.Complete)+" complete.\r\nNative checks: initial load, automatic refresh, research save, region and zone filters, invalid-export retention, file selection persistence, research survival after file changes, personal note persistence and search exclusion, collapsed/open details and table-only view.\r\nGuides: destination aliases, no-fixed-location objectives, all current objectives, multi-zone filters. QA rendered in an isolated data folder.");
 }
}
}
