using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Markup;
namespace LegendsCompanion {
public static class Palette {
 static System.Collections.Generic.Dictionary<SolidColorBrush,ColorSource> colors=new System.Collections.Generic.Dictionary<SolidColorBrush,ColorSource>();
 class ColorSource:DependencyObject {public static readonly DependencyProperty ValueProperty=DependencyProperty.Register("Value",typeof(Color),typeof(ColorSource));public Color Value{get{return (Color)GetValue(ValueProperty);}set{SetValue(ValueProperty,value);}}}
 static SolidColorBrush Create(){var brush=new SolidColorBrush();var source=new ColorSource();System.Windows.Data.BindingOperations.SetBinding(brush,SolidColorBrush.ColorProperty,new System.Windows.Data.Binding("Value"){Source=source});colors.Add(brush,source);return brush;}
 public static SolidColorBrush Background=Create(),Surface=Create(),Text=Create(),Muted=Create(),Border=Create(),Gold=Create(),Blue=Create(),Highlight=Create();
 public static void Set(bool dark){Paint(Background,ColorOf(dark?"#101824":"#F7F5EF"));Paint(Surface,ColorOf(dark?"#1B293B":"#FFFFFF"));Paint(Text,ColorOf(dark?"#EDF2F8":"#172C46"));Paint(Muted,ColorOf(dark?"#B6C3D4":"#516078"));Paint(Border,ColorOf(dark?"#3D5069":"#CED6E0"));Paint(Gold,ColorOf(dark?"#F3C45D":"#936500"));Paint(Blue,ColorOf(dark?"#79B5FF":"#235C9C"));Paint(Highlight,ColorOf(dark?"#483A1C":"#FFF0C5"));}
 static void Paint(SolidColorBrush brush,Color color){colors[brush].Value=color;}
 static Color ColorOf(string value){return (Color)ColorConverter.ConvertFromString(value);}
}
public partial class MainWindow {
 Button themeButton;
 void InitializeTheme(){
  Palette.Set(settings.DarkMode);
  var styles=(ResourceDictionary)XamlReader.Parse(@"<ResourceDictionary xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'>
<Style TargetType='TextBlock'><Setter Property='Foreground' Value='{DynamicResource Ink}'/></Style>
<Style TargetType='Button'><Setter Property='Background' Value='{DynamicResource Surface}'/><Setter Property='Foreground' Value='{DynamicResource Ink}'/><Setter Property='BorderBrush' Value='{DynamicResource Edge}'/><Setter Property='BorderThickness' Value='1'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='Button'><Border x:Name='B' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='{TemplateBinding BorderThickness}' CornerRadius='5' Padding='{TemplateBinding Padding}'><ContentPresenter HorizontalAlignment='Center' VerticalAlignment='Center'/></Border><ControlTemplate.Triggers><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='B' Property='BorderBrush' Value='{DynamicResource Gold}'/></Trigger><Trigger Property='IsPressed' Value='True'><Setter TargetName='B' Property='Background' Value='{DynamicResource Highlight}'/></Trigger><Trigger Property='IsEnabled' Value='False'><Setter Property='Opacity' Value='.5'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ToggleButton'><Setter Property='Background' Value='{DynamicResource Surface}'/><Setter Property='Foreground' Value='{DynamicResource Ink}'/><Setter Property='BorderBrush' Value='{DynamicResource Edge}'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ToggleButton'><Border x:Name='B' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='1' CornerRadius='5' Padding='{TemplateBinding Padding}'><ContentPresenter HorizontalAlignment='Center' VerticalAlignment='Center'/></Border><ControlTemplate.Triggers><Trigger Property='IsChecked' Value='True'><Setter TargetName='B' Property='Background' Value='{DynamicResource Highlight}'/><Setter TargetName='B' Property='BorderBrush' Value='{DynamicResource Gold}'/></Trigger><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='B' Property='BorderBrush' Value='{DynamicResource Gold}'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='TextBox'><Setter Property='Background' Value='{DynamicResource Surface}'/><Setter Property='Foreground' Value='{DynamicResource Ink}'/><Setter Property='CaretBrush' Value='{DynamicResource Ink}'/><Setter Property='BorderBrush' Value='{DynamicResource Edge}'/><Setter Property='Padding' Value='6'/></Style>
<Style TargetType='CheckBox'><Setter Property='Foreground' Value='{DynamicResource Ink}'/></Style>
<Style TargetType='Expander'><Setter Property='Foreground' Value='{DynamicResource Ink}'/></Style>
<Style TargetType='ComboBox'><Setter Property='Background' Value='{DynamicResource Surface}'/><Setter Property='Foreground' Value='{DynamicResource Ink}'/><Setter Property='BorderBrush' Value='{DynamicResource Edge}'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ComboBox'><Grid><ToggleButton Focusable='False' IsChecked='{Binding IsDropDownOpen, RelativeSource={RelativeSource TemplatedParent}, Mode=TwoWay}' Background='{TemplateBinding Background}' Padding='6'><Grid><Grid.ColumnDefinitions><ColumnDefinition Width='*'/><ColumnDefinition Width='16'/></Grid.ColumnDefinitions><ContentPresenter Content='{TemplateBinding SelectionBoxItem}' ContentTemplate='{TemplateBinding SelectionBoxItemTemplate}'/><TextBlock Grid.Column='1' Text=' ▾'/></Grid></ToggleButton><Popup x:Name='PART_Popup' Placement='Bottom' IsOpen='{TemplateBinding IsDropDownOpen}' AllowsTransparency='True' Focusable='False'><Border Background='{DynamicResource Surface}' BorderBrush='{DynamicResource Edge}' BorderThickness='1' MinWidth='{Binding ActualWidth, RelativeSource={RelativeSource TemplatedParent}}'><ScrollViewer MaxHeight='320'><ItemsPresenter/></ScrollViewer></Border></Popup></Grid></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ComboBoxItem'><Setter Property='Foreground' Value='{DynamicResource Ink}'/><Setter Property='Padding' Value='8,6'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ComboBoxItem'><Border x:Name='B' Background='{DynamicResource Surface}' Padding='{TemplateBinding Padding}'><ContentPresenter/></Border><ControlTemplate.Triggers><Trigger Property='IsHighlighted' Value='True'><Setter TargetName='B' Property='Background' Value='{DynamicResource Highlight}'/></Trigger><Trigger Property='IsSelected' Value='True'><Setter TargetName='B' Property='Background' Value='{DynamicResource Highlight}'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='DataGrid'><Setter Property='Background' Value='{DynamicResource Back}'/><Setter Property='Foreground' Value='{DynamicResource Ink}'/><Setter Property='RowBackground' Value='{DynamicResource Surface}'/><Setter Property='AlternatingRowBackground' Value='{DynamicResource Back}'/><Setter Property='BorderBrush' Value='{DynamicResource Edge}'/><Setter Property='HorizontalGridLinesBrush' Value='{DynamicResource Edge}'/><Setter Property='VerticalGridLinesBrush' Value='{DynamicResource Edge}'/></Style>
<Style TargetType='DataGridColumnHeader'><Setter Property='Background' Value='{DynamicResource Surface}'/><Setter Property='Foreground' Value='{DynamicResource Gold}'/><Setter Property='Padding' Value='6'/><Setter Property='BorderBrush' Value='{DynamicResource Edge}'/></Style>
<Style TargetType='DataGridCell'><Setter Property='Foreground' Value='{DynamicResource Ink}'/><Style.Triggers><Trigger Property='IsSelected' Value='True'><Setter Property='Background' Value='{DynamicResource Highlight}'/><Setter Property='Foreground' Value='{DynamicResource Ink}'/><Setter Property='BorderBrush' Value='{DynamicResource Gold}'/></Trigger></Style.Triggers></Style>
<Style TargetType='ContextMenu'><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ContextMenu'><Border Background='{DynamicResource Surface}' BorderBrush='{DynamicResource Edge}' BorderThickness='1' CornerRadius='6' Padding='4'><StackPanel IsItemsHost='True'/></Border></ControlTemplate></Setter.Value></Setter><Setter Property='Background' Value='{DynamicResource Surface}'/><Setter Property='Foreground' Value='{DynamicResource Ink}'/></Style>
<Style TargetType='MenuItem'><Setter Property='Foreground' Value='{DynamicResource Ink}'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='MenuItem'><Border x:Name='Item' Background='Transparent' Padding='12,7' CornerRadius='4'><ContentPresenter ContentSource='Header'/></Border><ControlTemplate.Triggers><Trigger Property='IsHighlighted' Value='True'><Setter TargetName='Item' Property='Background' Value='{DynamicResource Highlight}'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style x:Key='ScrollPage' TargetType='RepeatButton'><Setter Property='Focusable' Value='False'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='RepeatButton'><Border Background='Transparent'/></ControlTemplate></Setter.Value></Setter></Style>
<Style x:Key='ScrollGrip' TargetType='Thumb'><Setter Property='MinHeight' Value='24'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='Thumb'><Border x:Name='Grip' Background='{DynamicResource Edge}' Opacity='.55' CornerRadius='4' Margin='2'/><ControlTemplate.Triggers><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='Grip' Property='Background' Value='{DynamicResource Gold}'/><Setter TargetName='Grip' Property='Opacity' Value='1'/></Trigger><Trigger Property='IsDragging' Value='True'><Setter TargetName='Grip' Property='Background' Value='{DynamicResource Gold}'/><Setter TargetName='Grip' Property='Opacity' Value='1'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ScrollBar'><Setter Property='Width' Value='10'/><Setter Property='MinWidth' Value='0'/><Setter Property='Background' Value='Transparent'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ScrollBar'><Border Background='{TemplateBinding Background}' CornerRadius='5'><Track x:Name='PART_Track' Orientation='{TemplateBinding Orientation}' IsDirectionReversed='True'><Track.Resources><sys:Double xmlns:sys='clr-namespace:System;assembly=mscorlib' x:Key='{x:Static SystemParameters.VerticalScrollBarButtonHeightKey}'>48</sys:Double><sys:Double xmlns:sys='clr-namespace:System;assembly=mscorlib' x:Key='{x:Static SystemParameters.HorizontalScrollBarButtonWidthKey}'>48</sys:Double></Track.Resources><Track.DecreaseRepeatButton><RepeatButton Style='{StaticResource ScrollPage}' Command='ScrollBar.PageUpCommand'/></Track.DecreaseRepeatButton><Track.Thumb><Thumb Style='{StaticResource ScrollGrip}'/></Track.Thumb><Track.IncreaseRepeatButton><RepeatButton Style='{StaticResource ScrollPage}' Command='ScrollBar.PageDownCommand'/></Track.IncreaseRepeatButton></Track></Border><ControlTemplate.Triggers><Trigger Property='Orientation' Value='Horizontal'><Setter TargetName='PART_Track' Property='IsDirectionReversed' Value='False'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter><Style.Triggers><Trigger Property='Orientation' Value='Horizontal'><Setter Property='Width' Value='Auto'/><Setter Property='Height' Value='10'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ScrollBar'><Border Background='{TemplateBinding Background}' CornerRadius='5'><Track x:Name='PART_Track' Orientation='Horizontal' IsDirectionReversed='False'><Track.Resources><sys:Double xmlns:sys='clr-namespace:System;assembly=mscorlib' x:Key='{x:Static SystemParameters.VerticalScrollBarButtonHeightKey}'>48</sys:Double><sys:Double xmlns:sys='clr-namespace:System;assembly=mscorlib' x:Key='{x:Static SystemParameters.HorizontalScrollBarButtonWidthKey}'>48</sys:Double></Track.Resources><Track.DecreaseRepeatButton><RepeatButton Style='{StaticResource ScrollPage}' Command='ScrollBar.PageLeftCommand'/></Track.DecreaseRepeatButton><Track.Thumb><Thumb Style='{StaticResource ScrollGrip}' MinHeight='0' MinWidth='24'/></Track.Thumb><Track.IncreaseRepeatButton><RepeatButton Style='{StaticResource ScrollPage}' Command='ScrollBar.PageRightCommand'/></Track.IncreaseRepeatButton></Track></Border></ControlTemplate></Setter.Value></Setter></Trigger></Style.Triggers></Style>
<Style TargetType='Slider'><Setter Property='Background' Value='Transparent'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='Slider'><Grid Height='22' Background='Transparent'><Border Height='3' Background='{DynamicResource Edge}' CornerRadius='2' VerticalAlignment='Center' Margin='5,0'/><Track x:Name='PART_Track'><Track.DecreaseRepeatButton><RepeatButton Style='{StaticResource ScrollPage}' Command='Slider.DecreaseLarge'/></Track.DecreaseRepeatButton><Track.Thumb><Thumb Width='10' Height='10'><Thumb.Template><ControlTemplate TargetType='Thumb'><Border Background='{DynamicResource Edge}' BorderBrush='{DynamicResource Ink}' BorderThickness='.5' CornerRadius='5'/></ControlTemplate></Thumb.Template></Thumb></Track.Thumb><Track.IncreaseRepeatButton><RepeatButton Style='{StaticResource ScrollPage}' Command='Slider.IncreaseLarge'/></Track.IncreaseRepeatButton></Track></Grid></ControlTemplate></Setter.Value></Setter></Style>
</ResourceDictionary>");
  styles["Back"]=Palette.Background;styles["Surface"]=Palette.Surface;styles["Ink"]=Palette.Text;styles["Edge"]=Palette.Border;styles["Gold"]=Palette.Gold;styles["Highlight"]=Palette.Highlight;
  Resources.MergedDictionaries.Add(styles);Foreground=Palette.Text;
 }
 void ToggleTheme(){settings.DarkMode=!settings.DarkMode;Palette.Set(settings.DarkMode);themeButton.ToolTip=settings.DarkMode?"Switch to light mode":"Switch to dark mode";Data.Save(settingsPath,settings);}
}
}
