using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Threading;
using Microsoft.Win32;
using System.Windows.Interop;
namespace LegendsCompanion {
// Stable row identities allow FLIP movement without rebinding the research editor.
public class TilePanel:Panel {
 public double TileWidth=270,TileHeight=96; public ScrollViewer Host; public double DragWidth;
 bool VisibleAt(int i,int columns){if(Host==null||Host.ViewportHeight<=0)return true;double y=(i/columns)*TileHeight;return y+TileHeight>=Host.VerticalOffset-TileHeight&&y<=Host.VerticalOffset+Host.ViewportHeight+TileHeight;}
 protected override Size MeasureOverride(Size size){double w=DragWidth>0?DragWidth:Double.IsInfinity(size.Width)?TileWidth:size.Width;int n=Math.Max(1,(int)(w/TileWidth));double cell=w/n;for(int i=0;i<Children.Count;i++){var child=Children[i];bool visible=VisibleAt(i,n);var visibility=visible?Visibility.Visible:Visibility.Collapsed;if(child.Visibility!=visibility)child.Visibility=visibility;if(visible)child.Measure(new Size(cell,TileHeight));}return new Size(Double.IsInfinity(size.Width)?w:size.Width,Math.Ceiling((double)Children.Count/n)*TileHeight);}
 protected override Size ArrangeOverride(Size size){double layoutWidth=DragWidth>0?DragWidth:size.Width;int n=Math.Max(1,(int)(layoutWidth/TileWidth));double w=layoutWidth/n;for(int i=0;i<Children.Count;i++)if(Children[i].Visibility==Visibility.Visible)Children[i].Arrange(new Rect(i%n*w,i/n*TileHeight,w,TileHeight));return size;}
}
public partial class MainWindow {
 WrapPanel trackerToolbar;TilePanel tilePanel;ScrollViewer tileScroll,configuration;StackPanel configContent;Button configButton;CheckBox recentCheck,liveEnabled,popupsEnabled;TextBox combatPath;TextBlock tileCount,liveState;bool tableMode=false,configOpen=false;
 Dictionary<string,long> recentStamps=new Dictionary<string,long>();Dictionary<string,LiveNotice> liveNotices=new Dictionary<string,LiveNotice>();long recentSequence;DispatcherTimer highlightTimer;HashSet<string> highlighted=new HashSet<string>();
 Dictionary<string,Button> tileCache=new Dictionary<string,Button>(); Dictionary<string,string> tileSignatures=new Dictionary<string,string>(); Dictionary<string,Row> tileRows=new Dictionary<string,Row>();
 static Brush TileBlue=Palette.Gold;
 void BuildTrackerHeader(DockPanel root){
  var toolbar=new WrapPanel{Margin=new Thickness(0,0,0,5)};trackerToolbar=toolbar;DockPanel.SetDock(toolbar,Dock.Top);root.Children.Add(toolbar);
  
  filtersButton=Button("Filters",()=>{settings.FiltersHidden=!settings.FiltersHidden;settings.TableOnly=false;SetPresentation(true);});toolbar.Children.Add(filtersButton);
  tableButton=Button("Table",()=>{tableMode=!tableMode;tableButton.Content=tableMode?"Tiles":"Table";RenderTiles(false);});toolbar.Children.Add(tableButton);
  var more=new Button{Content="More ▾",Padding=new Thickness(8,4,8,4),Margin=new Thickness(0,0,4,4)};var menu=new ContextMenu();Action<string,Action> item=(label,action)=>{var m=new MenuItem{Header=label};m.Click+=(s,e)=>action();menu.Items.Add(m);};
  item("Check for updates",()=>{var check=CheckUpdates(true);});item("Category progress",()=>ShowText("Category progress",String.Join("\n",achievements.GroupBy(a=>a.Category).Select(g=>g.Key+": "+g.Count(a=>a.Complete)+" / "+g.Count()))));item("Research audit",()=>ShowText("Research coverage",String.Join("\n\n",joined.Select(r=>r.Achievement+": "+r.ResearchGaps))));item("Missing locations",()=>{region.SelectedIndex=0;RefreshZones();zone.SelectedItem="Unresearched";Apply();});item("Export visible CSV",Export);item("Route summary",ShowRoutes);item("Guide",Guide);more.ContextMenu=menu;more.Click+=(s,e)=>{menu.PlacementTarget=more;menu.IsOpen=true;};toolbar.Children.Add(more);
  foreach(Button b in toolbar.Children){b.Padding=new Thickness(7,4,7,4);b.Margin=new Thickness(0,0,4,4);}
  configContent=new StackPanel{Margin=new Thickness(6)};configuration=new ScrollViewer{Content=configContent,Visibility=Visibility.Collapsed,MaxHeight=0,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};DockPanel.SetDock(configuration,Dock.Top);var settingsFrame=new Border{Child=configuration,Background=Palette.Surface,BorderBrush=Palette.Border,BorderThickness=new Thickness(0,0,0,1),Padding=new Thickness(7),Margin=new Thickness(0,0,0,8)};settingsFrame.Effect=new System.Windows.Media.Effects.DropShadowEffect{BlurRadius=8,ShadowDepth=4,Opacity=.22,RenderingBias=System.Windows.Media.Effects.RenderingBias.Performance};settingsFrame.SetBinding(VisibilityProperty,new System.Windows.Data.Binding("Visibility"){Source=configuration});DockPanel.SetDock(settingsFrame,Dock.Top);root.Children.Add(settingsFrame);configContent.Children.Add(Text("Settings",17));
  configContent.Children.Add(Text("Achievement export",14));source=Input();source.Text=settings.SourcePath;source.ToolTip="Your character's achievement TXT export";configContent.Children.Add(source);var files=new WrapPanel();files.Children.Add(Button("Browse…",Browse));files.Children.Add(Button("Load / Refresh",()=>{if(ResolveEdits())LoadSource(true);}));configContent.Children.Add(files);source.KeyDown+=(s,e)=>{if(e.Key==System.Windows.Input.Key.Enter&&ResolveEdits())LoadSource(true);};
  liveEnabled=new CheckBox{Content="Enable live updates",IsChecked=settings.Live.Enabled,Margin=new Thickness(0,12,0,4)};configContent.Children.Add(liveEnabled);popupsEnabled=new CheckBox{Content="Show popups + sounds",IsChecked=settings.Live.PopupsEnabled,Margin=new Thickness(0,2,0,4)};configContent.Children.Add(popupsEnabled);configContent.Children.Add(Text("Combat log",13));combatPath=Input();combatPath.Text=settings.Live.Path;configContent.Children.Add(combatPath);var logButtons=new WrapPanel();logButtons.Children.Add(Button("Browse log…",()=>{var d=new OpenFileDialog{Filter="Combat logs (*.txt)|*.txt",FileName=combatPath.Text};if(d.ShowDialog(this)==true)combatPath.Text=d.FileName;}));logButtons.Children.Add(Button("Save live settings",SaveLiveConfiguration));logButtons.Children.Add(Button("Sound / popup options",()=>{if(live==null)return;live.Configure(this,()=>Data.Save(settingsPath,settings));combatPath.Text=settings.Live.Path;liveEnabled.IsChecked=settings.Live.Enabled;popupsEnabled.IsChecked=settings.Live.PopupsEnabled;}));configContent.Children.Add(logButtons);liveState=Text("Choose a combat log; in game use /log on.",12);configContent.Children.Add(liveState);BuildProfileControls(toolbar);var settingsTitle=configContent.Children.OfType<TextBlock>().FirstOrDefault(t=>t.Text=="Settings");if(settingsTitle!=null){configContent.Children.Remove(settingsTitle);configContent.Children.Insert(0,settingsTitle);}
  var strip=new WrapPanel{Margin=new Thickness(2,3,0,6)};DockPanel.SetDock(strip,Dock.Top);root.Children.Add(strip);recentCheck=new CheckBox{Content="Recent progress first",IsChecked=settings.RecentFirst,Margin=new Thickness(0,0,12,0)};configContent.Children.Add(recentCheck);recentCheck.Click+=(s,e)=>{settings.RecentFirst=recentCheck.IsChecked==true;Data.Save(settingsPath,settings);RenderTiles(true);};tileCount=Text("Choose your achievement export",12);strip.Children.Add(tileCount);
 }
 void SaveLiveConfiguration(){try{settings.Live.Path=combatPath.Text.Trim();settings.Live.Enabled=liveEnabled.IsChecked==true;settings.Live.PopupsEnabled=popupsEnabled.IsChecked==true;Data.Save(settingsPath,settings);if(live!=null)live.ApplySettings();liveState.Text=live==null?"Settings saved":live.Status;}catch(Exception e){liveState.Text="Could not save: "+e.Message;}}
 void ToggleConfiguration(){configOpen=!configOpen;configButton.ToolTip=configOpen?"Close settings":"Settings";configuration.BeginAnimation(FrameworkElement.MaxHeightProperty,null);configuration.MaxHeight=Double.PositiveInfinity;configuration.Visibility=configOpen?Visibility.Visible:Visibility.Collapsed;if(configOpen)configuration.ScrollToTop();} void InitializeTiles(){tilePanel=new TilePanel();tileScroll=new ScrollViewer{Content=tilePanel,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,HorizontalScrollBarVisibility=ScrollBarVisibility.Disabled};SourceInitialized+=(s,e)=>{var hwnd=PresentationSource.FromVisual(this) as HwndSource;if(hwnd!=null)hwnd.AddHook((IntPtr h,int message,IntPtr wp,IntPtr lp,ref bool handled)=>{if(message==0x0231)tilePanel.DragWidth=tilePanel.ActualWidth;if(message==0x0232){tilePanel.DragWidth=0;tilePanel.InvalidateMeasure();}return IntPtr.Zero;});};tilePanel.Host=tileScroll;tileScroll.ScrollChanged+=(s,e)=>{if(e.VerticalChange!=0||e.ViewportHeightChange!=0||e.ViewportWidthChange!=0)tilePanel.InvalidateMeasure();};bodyGrid.Children.Insert(0,tileScroll);grid.Visibility=Visibility.Collapsed;Loaded+=(s,e)=>{if(String.IsNullOrWhiteSpace(settings.SourcePath)&&!configOpen)ToggleConfiguration();};LocationChanged+=(s,e)=>PositionDetails();highlightTimer=new DispatcherTimer{Interval=TimeSpan.FromSeconds(4)};highlightTimer.Tick+=(s,e)=>{highlightTimer.Stop();highlighted.Clear();attentionActive=false;UpdateOpacity(true);RenderTiles(false);};}
 void LiveProgress(List<LiveNotice> notices){if(notices.Any(n=>filtered.Any(r=>r.A.Name==n.Name))){attentionActive=true;UpdateOpacity(false);}foreach(var n in notices){var row=joined.FirstOrDefault(r=>String.Equals(r.A.Name,n.Name,StringComparison.OrdinalIgnoreCase));if(row==null)continue;recentStamps[row.A.Key]=++recentSequence;liveNotices[row.A.Key]=n;highlighted.Add(row.A.Key);}RenderTiles(true);if(settings.RecentFirst&&notices.Any(n=>filtered.Any(r=>r.A.Name==n.Name)))tileScroll.ScrollToTop();highlightTimer.Stop();highlightTimer.Start();}
 bool exportAdvanced;Dictionary<string,int> stableTileOrder=new Dictionary<string,int>();
 void CaptureTileOrder(){if(tilePanel==null)return;stableTileOrder.Clear();int i=0;foreach(FrameworkElement tile in tilePanel.Children)if(tile.Tag is string)stableTileOrder[(string)tile.Tag]=i++;}
 void ExportProgress(List<Achievement> previous,List<Achievement> next){
  exportAdvanced=false;if(previous.Count==0)return;
  foreach(var a in next){var before=previous.FirstOrDefault(x=>x.Key==a.Key);if(before==null)continue;
   bool increased=(!before.Complete&&a.Complete)||a.Progress>before.Progress;
   if(!increased)increased=a.Requirements.Any(r=>r.Current.HasValue&&before.Requirements.Any(old=>old.Text.Split('\t')[0]==r.Text.Split('\t')[0]&&old.Current.HasValue&&r.Current>old.Current));
   if(increased){exportAdvanced=true;recentStamps[a.Key]=++recentSequence;highlighted.Add(a.Key);}
  }
 }
 void ClearLiveTiles(){attentionActive=false;UpdateOpacity(true);liveNotices.Clear();highlighted.Clear();RenderTiles(false);}
 TextBlock TileText(string value,int size,Brush color){return new TextBlock{Text=value,FontSize=size,Foreground=color,TextTrimming=TextTrimming.CharacterEllipsis,TextWrapping=TextWrapping.NoWrap,Margin=new Thickness(0,1,0,1),ToolTip=value};}
 bool batchRefresh;void RenderTiles(bool animate){if(tilePanel==null||batchRefresh)return;tileScroll.Visibility=tableMode?Visibility.Collapsed:Visibility.Visible;grid.Visibility=tableMode?Visibility.Visible:Visibility.Collapsed;UpdateFocusLine();if(tableMode)return;
  var old=new Dictionary<string,Point>();foreach(FrameworkElement el in tilePanel.Children){if(el.Visibility==Visibility.Visible&&el.Tag!=null)old[(string)el.Tag]=el.TranslatePoint(new Point(),tilePanel);}
  var desired=new List<Button>();IEnumerable<Row> rows=filtered;if(settings.RecentFirst)rows=rows.OrderByDescending(r=>recentStamps.ContainsKey(r.A.Key)?recentStamps[r.A.Key]:0).ThenBy(r=>stableTileOrder.ContainsKey(r.A.Key)?stableTileOrder[r.A.Key]:Int32.MaxValue);
  foreach(var row in rows){var r=row;bool hot=highlighted.Contains(r.A.Key);LiveNotice cachedNotice;liveNotices.TryGetValue(r.A.Key,out cachedNotice);string signature=hot+"|"+(editing!=null&&editing.A.Key==r.A.Key)+"|"+(cachedNotice==null?"":cachedNotice.Detail);Button cached;if(tileCache.TryGetValue(r.A.Key,out cached)&&tileRows[r.A.Key]==r&&tileSignatures[r.A.Key]==signature){desired.Add(cached);continue;}var content=new StackPanel{Margin=new Thickness(10,7,10,7)};var head=new DockPanel();var remaining=TileText(r.A.Remaining.HasValue?r.Remaining+" left":r.State,12,Palette.Muted);DockPanel.SetDock(remaining,Dock.Right);head.Children.Add(remaining);remaining.Margin=new Thickness(8,0,0,0);var name=TileText(r.A.Name,14,TileBlue);name.FontWeight=FontWeights.SemiBold;head.Children.Add(name);content.Children.Add(head);content.Children.Add(TileText(r.Location,12,Palette.Muted));content.Children.Add(TileText(r.Mobs,12,Palette.Muted));var line=new DockPanel{Margin=new Thickness(0,5,0,0)};var pct=TileText(r.Progress,12,TileBlue);pct.Margin=new Thickness(7,0,0,0);DockPanel.SetDock(pct,Dock.Right);line.Children.Add(pct);LiveNotice notice;if(liveNotices.TryGetValue(r.A.Key,out notice)){string label=notice.Complete?"Complete in log":"Live estimate";var estimate=TileText(label,11,Palette.Gold);estimate.ToolTip=notice.Detail;estimate.Margin=new Thickness(5,0,0,0);DockPanel.SetDock(estimate,Dock.Right);line.Children.Add(estimate);}line.Children.Add(new ProgressBar{Minimum=0,Maximum=100,Value=r.A.Progress*100,Height=5,VerticalAlignment=VerticalAlignment.Center,Foreground=hot?Palette.Gold:TileBlue,Background=Palette.Border,BorderThickness=new Thickness(0)});content.Children.Add(line);
   var border=new Border{Child=content,Background=hot?Palette.Highlight:Palette.Surface,CornerRadius=new CornerRadius(8),BorderThickness=new Thickness(editing!=null&&editing.A.Key==r.A.Key?2:1),BorderBrush=hot?Palette.Gold:editing!=null&&editing.A.Key==r.A.Key?TileBlue:Palette.Border};var button=new Button{Tag=r.A.Key,Content=border,Margin=new Thickness(3),Padding=new Thickness(0),Background=Brushes.Transparent,BorderThickness=new Thickness(0),HorizontalContentAlignment=HorizontalAlignment.Stretch,VerticalContentAlignment=VerticalAlignment.Stretch};button.ToolTip=r.A.Name+"\n"+r.Location+"\n"+r.Mobs;button.Click+=(s,e)=>SelectTrackerTile(r);var template=new ControlTemplate(typeof(Button));var presenter=new FrameworkElementFactory(typeof(ContentPresenter));presenter.SetValue(ContentPresenter.HorizontalAlignmentProperty,HorizontalAlignment.Stretch);template.VisualTree=presenter;button.Template=template;if(hot)PulseTile(border);var menu=new ContextMenu();var copy=new MenuItem{Header="Copy achievement"};copy.Click+=(s,e)=>Clipboard.SetText(r.A.Name+"\n"+r.Location+" · "+r.Mobs+"\n"+r.Progress+" · "+r.Remaining+" remaining");menu.Items.Add(copy);button.ContextMenu=menu;tileCache[r.A.Key]=button;tileRows[r.A.Key]=r;tileSignatures[r.A.Key]=signature;desired.Add(button);
  }
  var keep=new HashSet<Button>(desired);for(int i=tilePanel.Children.Count-1;i>=0;i--)if(!keep.Contains((Button)tilePanel.Children[i]))tilePanel.Children.RemoveAt(i);for(int i=0;i<desired.Count;i++){if(i<tilePanel.Children.Count&&tilePanel.Children[i]==desired[i])continue;tilePanel.Children.Remove(desired[i]);tilePanel.Children.Insert(i,desired[i]);}
  if(animate&&SystemParameters.ClientAreaAnimation){tilePanel.UpdateLayout();foreach(FrameworkElement el in tilePanel.Children){Point previous;if(!old.TryGetValue((string)el.Tag,out previous))continue;var now=el.TranslatePoint(new Point(),tilePanel);double top=tileScroll.VerticalOffset,bottom=top+tileScroll.ViewportHeight;if((previous.Y<top-96||previous.Y>bottom)&&(now.Y<top-96||now.Y>bottom))continue;if(previous==now)continue;var transform=new TranslateTransform();el.RenderTransform=transform;var ease=new CubicEase{EasingMode=EasingMode.EaseOut};transform.BeginAnimation(TranslateTransform.XProperty,new DoubleAnimation(previous.X-now.X,0,TimeSpan.FromMilliseconds(450)){EasingFunction=ease});transform.BeginAnimation(TranslateTransform.YProperty,new DoubleAnimation(previous.Y-now.Y,0,TimeSpan.FromMilliseconds(450)){EasingFunction=ease});}}
 }
 public void TrackerChecks(){
  var saved=filtered;var rows=joined.Take(3).ToList();if(rows.Count<2)throw new Exception("Tracker fixture needs two achievements");filtered=rows;settings.RecentFirst=true;RenderTiles(false);Edit(rows[0]);var original=editing;string baseline=EditorState();LiveProgress(new List<LiveNotice>{new LiveNotice{Name=rows[1].A.Name,Detail="Test estimate"}});if((string)((FrameworkElement)tilePanel.Children[0]).Tag!=rows[1].A.Key)throw new Exception("Recent tile did not move first");if(editing!=original||EditorState()!=baseline||HasActualEdits())throw new Exception("Progress changed the open editor");settings.RecentFirst=false;RenderTiles(false);if((string)((FrameworkElement)tilePanel.Children[0]).Tag!=rows[0].A.Key)throw new Exception("Default order not restored");filtered=rows.Take(1).ToList();LiveProgress(new List<LiveNotice>{new LiveNotice{Name=rows[1].A.Name,Detail="Filtered test"}});if(tilePanel.Children.Count!=1)throw new Exception("Live update bypassed filters");ClearLiveTiles();if(liveNotices.Count!=0)throw new Exception("Export reset retained estimates");filtered=saved;Edit(null);dirty=false;RenderTiles(false);
  var panel=new TilePanel();for(int i=0;i<12;i++)panel.Children.Add(new Border());panel.Measure(new Size(300,Double.PositiveInfinity));panel.Arrange(new Rect(0,0,300,1152));if(panel.Children[1].TranslatePoint(new Point(),panel).X!=0)throw new Exception("Narrow tile layout not single column");panel.Measure(new Size(900,Double.PositiveInfinity));panel.Arrange(new Rect(0,0,900,384));if(panel.Children[1].TranslatePoint(new Point(),panel).Y!=0||panel.Children[3].TranslatePoint(new Point(),panel).Y!=96)throw new Exception("Wide tile layout not wrapping");
 }
 public void CheckTileToggle(){
  ShrinkDetails();Width=340;UpdateLayout();var row=filtered.First();
  SelectTrackerTile(row);if(!detailsOpen||editing!=row)throw new Exception("Tile did not open");
  SelectTrackerTile(row);if(detailsOpen||editing!=null||Math.Abs(Width-340)>1)throw new Exception("Tile did not deselect and shrink");
 }
 void SelectTrackerTile(Row r){
  if(editing==r&&detailsOpen){
   if(!ResolveEdits())return;
   binding=true;grid.UnselectAllCells();grid.SelectedItem=null;binding=false;
   Edit(null);ShrinkDetails();RenderTiles(false);return;
  }
  if(editing!=r&&!ResolveEdits())return;
  Edit(r);binding=true;grid.SelectedItem=r;binding=false;OpenDetails();RenderTiles(false);
 }
 double compactWidth=0,compactLeft=0;
 void GrowForDetails(){if(ActualWidth>=850||WindowState==WindowState.Maximized)return;compactWidth=Width;compactLeft=Left;var area=SystemParameters.WorkArea;Width=Math.Min(area.Width,Math.Max(960,compactWidth*3));Left=Math.Max(area.Left,Math.Min(Left,area.Right-Width));}
 void RestoreTrackerWidth(){if(compactWidth<=0)return;Width=compactWidth;Left=compactLeft;compactWidth=0;}
 void PositionDetails(){}
}
}








