using System;
using System.Linq;
using System.Collections.Generic;
namespace LegendsCompanion {
public static class TravelGuide {
 static Dictionary<string,List<string>> edges=new Dictionary<string,List<string>>();
 static Dictionary<string,string> dru=new Dictionary<string,string>(),wiz=new Dictionary<string,string>();
 public const string Sources="Ports: https://eqlwiki.com/Rituals\nRoutes: adjacent-zone lists on the linked zone pages. Reviewed 2026-09-11. Fewest documented zone transitions; walking distance, danger and access can change the best choice.";
 static TravelGuide(){
  Add("South Kaladim","North Kaladim");Add("Felwithe","Southern Felwithe");Add("Nektulos Forest","Neriak Foreign Quarter");Add("Neriak Foreign Quarter","Neriak Commons");Add("Neriak Commons","Neriak Third Gate");
  Add("West Karana","Qeynos Hills|North Karana");Add("North Karana","East Karana|South Karana");Add("East Karana","Highpass Hold|Gorge of King Xorbb");Add("South Karana","Lake Rathetear|Splitpaw Lair");
  Add("Greater Faydark","Felwithe|Butcherblock Mountains|Lesser Faydark|Crushbone");Add("Lesser Faydark","Steamfont Mountains|Mistmoore Castle");Add("Butcherblock Mountains","South Kaladim|Dagnor's Cauldron");Add("Steamfont Mountains","Ak'Anon");Add("Dagnor's Cauldron","Estate of Unrest|Kedge Keep");
  Add("Lavastorm Mountains","Temple of Solusek Ro|Solusek's Eye|Nagafen's Lair|Najena|Nektulos Forest");Add("Toxxulia Forest","Kerra Island|Erudin|Paineel");Add("Paineel","The Hole|Warrens");Add("The Feerrott","Rathe Mountains|Oggok|Cazic-Thule|Plane of Fear|Innothule Swamp");Add("Misty Thicket","Rivervale|Runnyeye");Add("Gorge of King Xorbb","Runnyeye");Add("Rathe Mountains","Lake Rathetear");Add("Lake Rathetear","Arena");Add("Qeynos Hills","North Qeynos|Blackburrow|Surefall Glade");Add("West Commonlands","East Commonlands|Kithicor Forest|Befallen");
  Add("North Qeynos","South Qeynos|Qeynos Aqueducts");Add("Erudin","Erudin Palace");Add("Innothule Swamp","Grobb|Upper Guk|South Ro");Add("North Ro","East Freeport|East Commonlands|Oasis of Marr|New Sebilis Expedition");Add("South Ro","Oasis of Marr");Add("Kithicor Forest","Rivervale|Highpass Hold");Add("Everfrost Peaks","Halas|Blackburrow|Permafrost Caverns");Add("East Commonlands","Nektulos Forest|West Freeport");
  Port(dru,"Butcherblock Mountains","Circle of Butcherblock");Port(dru,"The Feerrott","Circle of Feerrott");Port(dru,"Lavastorm Mountains","Circle of Lavastorm");Port(dru,"Misty Thicket","Circle of Misty Thicket");Port(dru,"North Karana","Circle of North Karana");Port(dru,"South Ro","Circle of South Ro");Port(dru,"Steamfont Mountains","Circle of Steamfont");Port(dru,"Stonebrunt Mountains","Circle of Stonebrunt");Port(dru,"Surefall Glade","Circle of Surefall Glade");Port(dru,"Toxxulia Forest","Circle of Toxxulia");Port(dru,"West Commonlands","Circle of West Commons");
  Port(wiz,"Cazic-Thule","Cazic Temple Portal");Port(wiz,"Greater Faydark","Greater Faydark Portal");Port(wiz,"Nektulos Forest","Nektulos Portal");Port(wiz,"North Karana","North Karana Portal");Port(wiz,"North Ro","North Ro Portal");Port(wiz,"Stonebrunt Mountains","Stonebrunt Portal");Port(wiz,"Toxxulia Forest","Toxxulia Portal");Port(wiz,"West Commonlands","West Commons Portal");Port(wiz,"West Karana","West Karana Portal");Port(wiz,"Plane of Hate","Alter Plane: Hate");Port(wiz,"Plane of Sky","Alter Plane: Sky");
 }
 static void Port(Dictionary<string,string> d,string z,string spell){d[z]=spell;}
 static void Add(string a,string b){foreach(var z in b.Split('|')){if(!edges.ContainsKey(a))edges[a]=new List<string>();if(!edges.ContainsKey(z))edges[z]=new List<string>();edges[a].Add(z);edges[z].Add(a);}}
 static List<string> Path(string from,string to){var q=new Queue<List<string>>();q.Enqueue(new List<string>{from});var seen=new HashSet<string>{from};while(q.Count>0){var p=q.Dequeue();var last=p.Last();if(last==to)return p;if(!edges.ContainsKey(last))continue;foreach(var n in edges[last])if(seen.Add(n))q.Enqueue(p.Concat(new[]{n}).ToList());}return null;}
 static string ForClass(string zone,Dictionary<string,string> ports){var paths=ports.Select(p=>new{Spell=p.Value,Path=Path(p.Key,zone)}).Where(p=>p.Path!=null).OrderBy(p=>p.Path.Count).ThenBy(p=>p.Spell).ToList();if(paths.Count==0)return "Route not yet verified";var best=paths[0];return best.Spell+" — "+String.Join(" → ",best.Path);}
 public static string ForZone(string zone){zone=Guides.Zone(zone);if(zone=="Plane of Sky")return "Druid: East Commons portal → East Freeport → click the orb → Plane of Sky\nWizard: West Commons Portal → East Commons → East Freeport → click the orb → Plane of Sky\nDruid arrival and East Freeport orb location reported by user in Legends (2026-09-11).";string s="Druid: "+ForClass(zone,dru)+"\nWizard: "+ForClass(zone,wiz);if(zone=="Plane of Hate")s+="\nWizard reagent: Fuligan Soulstone of Innoruuk; arrange planar access.";if(zone=="Plane of Sky")s+="\nWizard reagent: Cloudy Stone of Veeshan; arrange planar access.";if(zone=="The Hole"||zone=="Plane of Fear"||zone=="Kedge Keep")s+="\nCheck dungeon/planar entry requirements before travel.";return s;}
 public static string ForFarm(Farm f){return !String.IsNullOrWhiteSpace(f.PortRoute)?f.PortRoute:String.Join("\n",(f.Zone??"").Split(new[]{',',';'},StringSplitOptions.RemoveEmptyEntries).Select(z=>ForZone(z.Trim())));}
 public static bool HasRoute(string zone){return !ForZone(zone).Contains("Route not yet verified");}
}
}
